// AUTO-GENERATED by `npm run codegen`. Do not edit by hand.
// Source of truth: lib/schemas/*.ts + lib/sdk/manifest.ts

package pharmacopeia

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// DefaultBaseURL is the public pharmacopeia API base (origin + /api/v1).
const DefaultBaseURL = "https://pharmacopeia.dev/api/v1"

// Client is a thin, typed client for the pharmacopeia API. Every method
// returns the same shape the API serves; non-2xx responses return an
// *APIError carrying the API error code and details.
type Client struct {
	BaseURL    string
	HTTPClient *http.Client
	// APIKey, when set, is sent as "Authorization: Bearer <APIKey>".
	APIKey  string
	Headers map[string]string
}

// Option configures a Client.
type Option func(*Client)

// WithBaseURL overrides the API base URL.
func WithBaseURL(baseURL string) Option {
	return func(c *Client) { c.BaseURL = baseURL }
}

// WithAPIKey sets the bearer token used for key-gated endpoints.
func WithAPIKey(apiKey string) Option {
	return func(c *Client) { c.APIKey = apiKey }
}

// WithHTTPClient supplies a custom *http.Client.
func WithHTTPClient(hc *http.Client) Option {
	return func(c *Client) { c.HTTPClient = hc }
}

// NewClient builds a Client, applying any options over the defaults.
func NewClient(opts ...Option) *Client {
	c := &Client{BaseURL: DefaultBaseURL, HTTPClient: http.DefaultClient}
	for _, opt := range opts {
		opt(c)
	}
	if c.HTTPClient == nil {
		c.HTTPClient = http.DefaultClient
	}
	return c
}

// APIError is returned when the API responds with a non-2xx status.
type APIError struct {
	Status  int
	Code    string
	Message string
	Details interface{}
}

func (e *APIError) Error() string {
	if e.Code != "" {
		return fmt.Sprintf("pharmacopeia: %s (%s, status %d)", e.Message, e.Code, e.Status)
	}
	return fmt.Sprintf("pharmacopeia: %s (status %d)", e.Message, e.Status)
}

// cloneValues copies caller-supplied query values so required params can
// be layered on without mutating the caller's map.
func cloneValues(in url.Values) url.Values {
	out := url.Values{}
	for k, vs := range in {
		for _, v := range vs {
			out.Add(k, v)
		}
	}
	return out
}

func (c *Client) do(method, path string, query url.Values, body, out interface{}) error {
	endpoint := strings.TrimRight(c.BaseURL, "/") + path
	if len(query) > 0 {
		endpoint += "?" + query.Encode()
	}

	var reader io.Reader
	if body != nil {
		buf, err := json.Marshal(body)
		if err != nil {
			return err
		}
		reader = bytes.NewReader(buf)
	}

	req, err := http.NewRequest(method, endpoint, reader)
	if err != nil {
		return err
	}
	req.Header.Set("Accept", "application/json")
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	if c.APIKey != "" {
		req.Header.Set("Authorization", "Bearer "+c.APIKey)
	}
	for k, v := range c.Headers {
		req.Header.Set(k, v)
	}

	res, err := c.HTTPClient.Do(req)
	if err != nil {
		return err
	}
	defer res.Body.Close()

	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}

	if res.StatusCode < 200 || res.StatusCode >= 300 {
		apiErr := &APIError{Status: res.StatusCode, Message: res.Status}
		var envelope struct {
			Error struct {
				Code    string      `json:"code"`
				Message string      `json:"message"`
				Details interface{} `json:"details"`
			} `json:"error"`
		}
		if json.Unmarshal(data, &envelope) == nil && envelope.Error.Message != "" {
			apiErr.Code = envelope.Error.Code
			apiErr.Message = envelope.Error.Message
			apiErr.Details = envelope.Error.Details
		}
		return apiErr
	}

	if out != nil {
		if err := json.Unmarshal(data, out); err != nil {
			return err
		}
	}
	return nil
}

// ListDrugs List drugs (paginated), optionally filtered by class or ingredient.
func (c *Client) ListDrugs(opts url.Values) (*DrugListResponse, error) {
	query := cloneValues(opts)
	var out DrugListResponse
	if err := c.do("GET", "/drugs", query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDrug Fetch a single drug by slug.
func (c *Client) GetDrug(slug string, opts url.Values) (*Drug, error) {
	query := cloneValues(opts)
	var out Drug
	if err := c.do("GET", "/drug/" + url.PathEscape(slug), query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDrugsBatch Fetch up to 100 drug records in a single round-trip. Returns the full records found plus the slugs that did not resolve.
func (c *Client) GetDrugsBatch(body DrugsBatchRequest) (*DrugsBatchResponse, error) {
	var out DrugsBatchResponse
	if err := c.do("POST", "/drugs/batch", nil, body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDrugInteractions List known interactions for a drug.
func (c *Client) GetDrugInteractions(slug string) (*DrugInteractionsResponse, error) {
	var out DrugInteractionsResponse
	if err := c.do("GET", "/drug/" + url.PathEscape(slug) + "/interactions", nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDrugHistory Dataset time-travel: the drug's current-snapshot provenance plus its change-event timeline (newest first). Pin ?asOf= to trim the timeline to a past instant. Leans on provenance + the changelog; no separate version store.
func (c *Client) GetDrugHistory(slug string, opts url.Values) (*DrugHistoryResponse, error) {
	query := cloneValues(opts)
	var out DrugHistoryResponse
	if err := c.do("GET", "/drug/" + url.PathEscape(slug) + "/history", query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSimilarDrugs Structurally similar drugs (Tanimoto over 2D fingerprints).
func (c *Client) GetSimilarDrugs(slug string) (*SimilarDrugsResponse, error) {
	var out SimilarDrugsResponse
	if err := c.do("GET", "/drug/" + url.PathEscape(slug) + "/similar", nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListClasses List drug classes (paginated).
func (c *Client) ListClasses(opts url.Values) (*ClassListResponse, error) {
	query := cloneValues(opts)
	var out ClassListResponse
	if err := c.do("GET", "/classes", query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetClass Fetch a single drug class plus the drugs it contains.
func (c *Client) GetClass(slug string) (*ClassDetailResponse, error) {
	var out ClassDetailResponse
	if err := c.do("GET", "/class/" + url.PathEscape(slug), nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListIngredients List active ingredients (paginated).
func (c *Client) ListIngredients(opts url.Values) (*IngredientListResponse, error) {
	query := cloneValues(opts)
	var out IngredientListResponse
	if err := c.do("GET", "/ingredients", query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetIngredient Fetch a single ingredient by slug.
func (c *Client) GetIngredient(slug string) (*Ingredient, error) {
	var out Ingredient
	if err := c.do("GET", "/ingredient/" + url.PathEscape(slug), nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListBrands Brand → generic crosswalk for every brand in the dataset.
func (c *Client) ListBrands() (*BrandsResponse, error) {
	var out BrandsResponse
	if err := c.do("GET", "/brands", nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetStats Dataset counts and version metadata.
func (c *Client) GetStats() (*Stats, error) {
	var out Stats
	if err := c.do("GET", "/stats", nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetHealth Liveness + dataset-version probe. Tiny payload for monitors and clients.
func (c *Client) GetHealth() (*HealthResponse, error) {
	var out HealthResponse
	if err := c.do("GET", "/health", nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Search Full-text search across drugs, classes, and ingredients.
func (c *Client) Search(q string, opts url.Values) (*SearchResponse, error) {
	query := cloneValues(opts)
	query.Set("q", q)
	var out SearchResponse
	if err := c.do("GET", "/search", query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// CheckInteractions Check a set of 2–20 drug slugs for pairwise interactions.
func (c *Client) CheckInteractions(body InteractionCheckRequest) (*InteractionCheckResponse, error) {
	var out InteractionCheckResponse
	if err := c.do("POST", "/interactions/check", nil, body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// StructureSearch Rank drugs in the dataset by 2D Tanimoto similarity to a caller-supplied SMILES. Structural proximity only.
func (c *Client) StructureSearch(body StructureSearchRequest) (*StructureSearchResponse, error) {
	var out StructureSearchResponse
	if err := c.do("POST", "/structure-search", nil, body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDrugShortages FDA shortage entries (active, resolved, discontinuation) for a drug. Reference statistics only.
func (c *Client) GetDrugShortages(slug string) (*DrugShortagesResponse, error) {
	var out DrugShortagesResponse
	if err := c.do("GET", "/drug/" + url.PathEscape(slug) + "/shortages", nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListShortages Every shortage entry across the dataset, sorted by drug then presentation.
func (c *Client) ListShortages() (*ShortagesResponse, error) {
	var out ShortagesResponse
	if err := c.do("GET", "/shortages", nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDrugAdverseEvents Aggregate FAERS report counts for a drug — top reactions by reporting volume. NOT incidence rates, signals, or causality.
func (c *Client) GetDrugAdverseEvents(slug string) (*AdverseEventStatsResponse, error) {
	var out AdverseEventStatsResponse
	if err := c.do("GET", "/drug/" + url.PathEscape(slug) + "/adverse-events", nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDrugLiterature Curated PubMed references for a drug, pinned to MeSH major topic at ingest time.
func (c *Client) GetDrugLiterature(slug string) (*DrugLiteratureResponse, error) {
	var out DrugLiteratureResponse
	if err := c.do("GET", "/drug/" + url.PathEscape(slug) + "/literature", nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDrugTrials ClinicalTrials.gov registrations naming the drug as an intervention — freshest sample plus total registry match count. NOT evidence of efficacy or safety.
func (c *Client) GetDrugTrials(slug string) (*DrugTrialsResponse, error) {
	var out DrugTrialsResponse
	if err := c.do("GET", "/drug/" + url.PathEscape(slug) + "/trials", nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDrugPharmacogenomics CPIC-curated drug–gene pairs with evidence levels and guideline links. Evidence metadata only — never testing or dosing guidance.
func (c *Client) GetDrugPharmacogenomics(slug string) (*DrugPgxResponse, error) {
	var out DrugPgxResponse
	if err := c.do("GET", "/drug/" + url.PathEscape(slug) + "/pharmacogenomics", nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListReactions Browse MedDRA Preferred Terms reported to FAERS across the dataset, ordered by total reporting volume. Reference statistics only — NOT a symptom checker.
func (c *Client) ListReactions(opts url.Values) (*ReactionsListResponse, error) {
	query := cloneValues(opts)
	var out ReactionsListResponse
	if err := c.do("GET", "/reactions", query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetReaction Fetch one MedDRA Preferred Term with its per-drug breakdown (count + share of matched FAERS reports), related reactions ranked by Jaccard similarity over the drug-id sets, and optional reference metadata — NLM MeSH descriptor id, scope note, tree position, and recent PubMed papers on the term as a MeSH major topic. Alias slugs 301-redirect to canonical.
func (c *Client) GetReaction(slug string) (*ReactionResponse, error) {
	var out ReactionResponse
	if err := c.do("GET", "/reaction/" + url.PathEscape(slug), nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListConditions Browse ICD-10-CM conditions joined to the drugs labeled for them, ordered by number of labeled drugs. A reference reverse index of labeled uses — NOT a treatment recommendation.
func (c *Client) ListConditions(opts url.Values) (*ConditionsListResponse, error) {
	query := cloneValues(opts)
	var out ConditionsListResponse
	if err := c.do("GET", "/conditions", query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCondition Fetch one ICD-10-CM condition with the drugs labeled for it (each carrying the verbatim indication text that produced the link) and related conditions ranked by Jaccard similarity over the drug-id sets.
func (c *Client) GetCondition(slug string) (*ConditionResponse, error) {
	var out ConditionResponse
	if err := c.do("GET", "/condition/" + url.PathEscape(slug), nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// SemanticSearch Meaning-based retrieval over drug-record passages. Embedding-backed when available; lexical fallback otherwise — `method` in the response reports which.
func (c *Client) SemanticSearch(q string, opts url.Values) (*SemanticSearchResponse, error) {
	query := cloneValues(opts)
	query.Set("q", q)
	var out SemanticSearchResponse
	if err := c.do("GET", "/semantic-search", query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GroundedRetrieval Key-gated retrieval tier for LLM consumers: same passages as /semantic-search plus per-span citations carrying full provenance (source URL, content hash, extraction timestamp, confidence).
func (c *Client) GroundedRetrieval(body GroundedRequest) (*GroundedResponse, error) {
	var out GroundedResponse
	if err := c.do("POST", "/grounded", nil, body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListWebhooks List the webhook endpoints registered by the calling API key.
func (c *Client) ListWebhooks() (*WebhooksListResponse, error) {
	var out WebhooksListResponse
	if err := c.do("GET", "/webhooks", nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateWebhook Register a webhook endpoint. The response includes the HMAC signing secret exactly once — store it.
func (c *Client) CreateWebhook(body WebhookCreateRequest) (*WebhookEndpointCreated, error) {
	var out WebhookEndpointCreated
	if err := c.do("POST", "/webhooks", nil, body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteWebhook Delete a webhook endpoint owned by the calling API key.
func (c *Client) DeleteWebhook(id string) (*WebhookDeleteResponse, error) {
	var out WebhookDeleteResponse
	if err := c.do("DELETE", "/webhooks/" + url.PathEscape(id), nil, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// ListChangelog Recent record-level changes (typed mirror of /feed.xml and /feed.json).
func (c *Client) ListChangelog(opts url.Values) (*ChangelogResponse, error) {
	query := cloneValues(opts)
	var out ChangelogResponse
	if err := c.do("GET", "/changelog", query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
