// AUTO-GENERATED by `npm run codegen`. Do not edit by hand.
// Source of truth: lib/schemas/*.ts + lib/sdk/manifest.ts

package pharmacopeia

type Jurisdiction string

const (
	JurisdictionUSFDA Jurisdiction = "US-FDA"
	JurisdictionEUEMA Jurisdiction = "EU-EMA"
	JurisdictionUKMHRA Jurisdiction = "UK-MHRA"
	JurisdictionCAHC Jurisdiction = "CA-HC"
)

type Severity string

const (
	SeverityContraindicated Severity = "contraindicated"
	SeverityMajor Severity = "major"
	SeverityModerate Severity = "moderate"
	SeverityMinor Severity = "minor"
	SeverityUnknown Severity = "unknown"
)

type DeaSchedule string

const (
	DeaScheduleI DeaSchedule = "I"
	DeaScheduleII DeaSchedule = "II"
	DeaScheduleIII DeaSchedule = "III"
	DeaScheduleIV DeaSchedule = "IV"
	DeaScheduleV DeaSchedule = "V"
)

type DrugClassKind string

const (
	DrugClassKindAtc DrugClassKind = "atc"
	DrugClassKindMoa DrugClassKind = "moa"
	DrugClassKindEpc DrugClassKind = "epc"
	DrugClassKindPe DrugClassKind = "pe"
	DrugClassKindPharm DrugClassKind = "pharm"
	DrugClassKindMesh DrugClassKind = "mesh"
)

type Provenance struct {
	SourceUrl string `json:"sourceUrl"`
	SourceHash string `json:"sourceHash"`
	ExtractedAt string `json:"extractedAt"`
	Extractor string `json:"extractor"`
	Confidence float64 `json:"confidence"`
}

type Pagination struct {
	Total int `json:"total"`
	Limit int `json:"limit"`
	Offset int `json:"offset"`
}

type ApiError struct {
	Error struct {
		Code string `json:"code"`
		Message string `json:"message"`
		Details interface{} `json:"details,omitempty"`
	} `json:"error"`
}

type DrugRef struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
}

type Indication struct {
	Text string `json:"text"`
	Icd10 []string `json:"icd10"`
	Snomed []string `json:"snomed"`
}

type Contraindication struct {
	Text string `json:"text"`
	Severity Severity `json:"severity"`
}

type Dosing struct {
	Route string `json:"route"`
	Population string `json:"population"`
	Condition *string `json:"condition,omitempty"`
	Dose string `json:"dose"`
	Frequency *string `json:"frequency,omitempty"`
	MaxDose *string `json:"maxDose,omitempty"`
	Notes *string `json:"notes,omitempty"`
}

type Pharmacokinetics struct {
	HalfLife *string `json:"halfLife,omitempty"`
	TMax *string `json:"tMax,omitempty"`
	Bioavailability *string `json:"bioavailability,omitempty"`
	ProteinBinding *string `json:"proteinBinding,omitempty"`
	Metabolism *string `json:"metabolism,omitempty"`
	Excretion *string `json:"excretion,omitempty"`
}

type Mechanism struct {
	Summary string `json:"summary"`
	Targets []string `json:"targets"`
}

type Approval struct {
	Date string `json:"date"`
	ApplicationNumber string `json:"applicationNumber"`
	Type string `json:"type"`
	Sponsor *string `json:"sponsor,omitempty"`
}

type LabelSections struct {
	BoxedWarning *string `json:"boxedWarning,omitempty"`
	DosageAndAdministration *string `json:"dosageAndAdministration,omitempty"`
	WarningsAndPrecautions *string `json:"warningsAndPrecautions,omitempty"`
	AdverseReactions *string `json:"adverseReactions,omitempty"`
	UseInSpecificPopulations *string `json:"useInSpecificPopulations,omitempty"`
	Overdosage *string `json:"overdosage,omitempty"`
}

type ControlledSubstance struct {
	Schedule DeaSchedule `json:"schedule"`
	Narcotic *bool `json:"narcotic,omitempty"`
	Description string `json:"description"`
}

type OrangeBook struct {
	TeCode *string `json:"teCode,omitempty"`
	ReferenceListed *bool `json:"referenceListed,omitempty"`
	GenericAvailable bool `json:"genericAvailable"`
	Description string `json:"description"`
}

type Identifier struct {
	Rxcui *string `json:"rxcui,omitempty"`
	Ndc []string `json:"ndc"`
	Atc []string `json:"atc"`
	Drugbank *string `json:"drugbank,omitempty"`
	Chembl *string `json:"chembl,omitempty"`
	Pubchem *string `json:"pubchem,omitempty"`
	Unii *string `json:"unii,omitempty"`
}

type ChemicalStructure struct {
	Smiles string `json:"smiles"`
	InchiKey *string `json:"inchiKey,omitempty"`
	IupacName *string `json:"iupacName,omitempty"`
	PubchemCid *int `json:"pubchemCid,omitempty"`
	StructureSvgPath string `json:"structureSvgPath"`
	Provenance Provenance `json:"provenance"`
}

type DrugClassRef struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
	Kind DrugClassKind `json:"kind"`
	Code *string `json:"code,omitempty"`
}

type DrugClassParent struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
}

type DrugClass struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
	Kind DrugClassKind `json:"kind"`
	Code *string `json:"code,omitempty"`
	Description *string `json:"description,omitempty"`
	Parent *DrugClassParent `json:"parent,omitempty"`
	DrugCount int `json:"drugCount"`
	Provenance Provenance `json:"provenance"`
}

type IngredientRef struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
	Strength *string `json:"strength,omitempty"`
}

type Ingredient struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
	Synonyms []string `json:"synonyms"`
	Rxcui *string `json:"rxcui,omitempty"`
	Unii *string `json:"unii,omitempty"`
	Smiles *string `json:"smiles,omitempty"`
	Inchikey *string `json:"inchikey,omitempty"`
	MolecularFormula *string `json:"molecularFormula,omitempty"`
	MolecularWeight *float64 `json:"molecularWeight,omitempty"`
	DrugCount int `json:"drugCount"`
	Provenance Provenance `json:"provenance"`
}

type DrugSummary struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
	Synonyms []string `json:"synonyms"`
	Jurisdiction Jurisdiction `json:"jurisdiction"`
	Ingredients []IngredientRef `json:"ingredients"`
	Brands []string `json:"brands"`
	Classes []DrugClassRef `json:"classes"`
	ShortDescription *string `json:"shortDescription,omitempty"`
}

type Drug struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
	Synonyms []string `json:"synonyms"`
	Jurisdiction Jurisdiction `json:"jurisdiction"`
	Ingredients []IngredientRef `json:"ingredients"`
	Brands []string `json:"brands"`
	Classes []DrugClassRef `json:"classes"`
	ShortDescription *string `json:"shortDescription,omitempty"`
	Mechanism *Mechanism `json:"mechanism,omitempty"`
	Indications []Indication `json:"indications"`
	Contraindications []Contraindication `json:"contraindications"`
	Dosing []Dosing `json:"dosing"`
	Pharmacokinetics *Pharmacokinetics `json:"pharmacokinetics,omitempty"`
	ApprovalHistory []Approval `json:"approvalHistory"`
	PatientSummary *string `json:"patientSummary,omitempty"`
	InteractionsNarrative *string `json:"interactionsNarrative,omitempty"`
	LabelSections *LabelSections `json:"labelSections,omitempty"`
	ControlledSubstance *ControlledSubstance `json:"controlledSubstance,omitempty"`
	OrangeBook *OrangeBook `json:"orangeBook,omitempty"`
	Identifiers Identifier `json:"identifiers"`
	Chemical *ChemicalStructure `json:"chemical,omitempty"`
	Provenance Provenance `json:"provenance"`
}

type DrugsBatchRequest struct {
	Slugs []string `json:"slugs"`
}

type DrugsBatchResponse struct {
	Found []Drug `json:"found"`
	Missing []string `json:"missing"`
	Total int `json:"total"`
}

type Interaction struct {
	DrugA string `json:"drugA"`
	DrugB string `json:"drugB"`
	Severity Severity `json:"severity"`
	Mechanism *string `json:"mechanism,omitempty"`
	Description string `json:"description"`
	Recommendation *string `json:"recommendation,omitempty"`
	EvidenceSpan *string `json:"evidenceSpan,omitempty"`
	Provenance Provenance `json:"provenance"`
}

type InteractionSummary struct {
	Contraindicated int `json:"contraindicated"`
	Major int `json:"major"`
	Moderate int `json:"moderate"`
	Minor int `json:"minor"`
	Unknown int `json:"unknown"`
}

type InteractionCheckRequest struct {
	Drugs []string `json:"drugs"`
}

type InteractionCheckResponse struct {
	Input []string `json:"input"`
	Pairs []Interaction `json:"pairs"`
	Summary InteractionSummary `json:"summary"`
}

type Stats struct {
	Drugs int `json:"drugs"`
	Classes int `json:"classes"`
	Ingredients int `json:"ingredients"`
	Interactions int `json:"interactions"`
	Indications int `json:"indications"`
	Version string `json:"version"`
	UpdatedAt string `json:"updatedAt"`
}

type HealthResponse struct {
	Status string `json:"status"`
	Version string `json:"version"`
	UpdatedAt string `json:"updatedAt"`
	Time string `json:"time"`
	Uptime *int `json:"uptime,omitempty"`
	Repository string `json:"repository"`
	Commit *string `json:"commit,omitempty"`
	Region *string `json:"region,omitempty"`
}

type SimilarDrugResult struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
	Score float64 `json:"score"`
	ClassName *string `json:"className,omitempty"`
}

type BrandEntry struct {
	Brand string `json:"brand"`
	Drugs []DrugRef `json:"drugs"`
}

type SearchResult struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
	Kind string `json:"kind"`
	Description *string `json:"description,omitempty"`
}

type DrugListResponse struct {
	Items []DrugSummary `json:"items"`
	Pagination Pagination `json:"pagination"`
}

type ClassListResponse struct {
	Items []DrugClass `json:"items"`
	Pagination Pagination `json:"pagination"`
}

type IngredientListResponse struct {
	Items []Ingredient `json:"items"`
	Pagination Pagination `json:"pagination"`
}

type DrugInteractionsResponse struct {
	Drug DrugRef `json:"drug"`
	Interactions []Interaction `json:"interactions"`
	Total int `json:"total"`
}

type SimilarDrugsResponse struct {
	Drug DrugRef `json:"drug"`
	Method string `json:"method"`
	Similar []SimilarDrugResult `json:"similar"`
	Total int `json:"total"`
}

type ClassDetailResponse struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
	Kind DrugClassKind `json:"kind"`
	Code *string `json:"code,omitempty"`
	Description *string `json:"description,omitempty"`
	Parent *DrugClassParent `json:"parent,omitempty"`
	DrugCount int `json:"drugCount"`
	Provenance Provenance `json:"provenance"`
	Drugs []DrugSummary `json:"drugs"`
}

type BrandsResponse struct {
	Brands []BrandEntry `json:"brands"`
	Total int `json:"total"`
}

type SearchResponse struct {
	Query string `json:"query"`
	Results []SearchResult `json:"results"`
	Total int `json:"total"`
}

type StructureMatch struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
	Score float64 `json:"score"`
	ClassName *string `json:"className,omitempty"`
	Smiles string `json:"smiles"`
}

type StructureSearchRequest struct {
	Smiles string `json:"smiles"`
	Limit int `json:"limit"`
	Threshold float64 `json:"threshold"`
}

type StructureSearchResponse struct {
	Query struct {
		Smiles string `json:"smiles"`
		Limit int `json:"limit"`
		Threshold float64 `json:"threshold"`
	} `json:"query"`
	Method string `json:"method"`
	Total int `json:"total"`
	Results []StructureMatch `json:"results"`
}

type ChangelogKind string

const (
	ChangelogKindDrug ChangelogKind = "drug"
	ChangelogKindClass ChangelogKind = "class"
	ChangelogKindIngredient ChangelogKind = "ingredient"
	ChangelogKindInteraction ChangelogKind = "interaction"
	ChangelogKindStructure ChangelogKind = "structure"
	ChangelogKindDataset ChangelogKind = "dataset"
	ChangelogKindEndpoint ChangelogKind = "endpoint"
)

type ChangelogAction string

const (
	ChangelogActionAdded ChangelogAction = "added"
	ChangelogActionUpdated ChangelogAction = "updated"
	ChangelogActionRemoved ChangelogAction = "removed"
	ChangelogActionReleased ChangelogAction = "released"
)

type ChangelogEntry struct {
	Id string `json:"id"`
	Kind ChangelogKind `json:"kind"`
	Action ChangelogAction `json:"action"`
	EntitySlug *string `json:"entitySlug,omitempty"`
	Title string `json:"title"`
	Summary string `json:"summary"`
	Timestamp string `json:"timestamp"`
	Url string `json:"url"`
	Sources []string `json:"sources"`
	Tags []string `json:"tags"`
}

type ChangelogResponse struct {
	Entries []ChangelogEntry `json:"entries"`
	Total int `json:"total"`
}

type ShortageStatus string

const (
	ShortageStatusActive ShortageStatus = "active"
	ShortageStatusResolved ShortageStatus = "resolved"
	ShortageStatusDiscontinuation ShortageStatus = "discontinuation"
	ShortageStatusToBeDiscontinued ShortageStatus = "to-be-discontinued"
)

type ShortageEntry struct {
	Drug string `json:"drug"`
	Status ShortageStatus `json:"status"`
	Presentation string `json:"presentation"`
	Sponsor *string `json:"sponsor,omitempty"`
	Reason *string `json:"reason,omitempty"`
	TherapeuticCategory *string `json:"therapeuticCategory,omitempty"`
	FdaUpdatedAt string `json:"fdaUpdatedAt"`
	Provenance Provenance `json:"provenance"`
}

type DrugShortagesResponse struct {
	Drug struct {
		Slug string `json:"slug"`
		Name string `json:"name"`
	} `json:"drug"`
	Entries []ShortageEntry `json:"entries"`
	AnyActive bool `json:"anyActive"`
	Total int `json:"total"`
}

type ShortagesResponse struct {
	Entries []ShortageEntry `json:"entries"`
	Total int `json:"total"`
}

type AdverseEventReport struct {
	Reaction string `json:"reaction"`
	Count int `json:"count"`
}

type AdverseEventStats struct {
	Drug string `json:"drug"`
	TotalReports int `json:"totalReports"`
	TopReactions []AdverseEventReport `json:"topReactions"`
	WindowStart *string `json:"windowStart,omitempty"`
	WindowEnd *string `json:"windowEnd,omitempty"`
	Disclaimer string `json:"disclaimer"`
	Provenance Provenance `json:"provenance"`
}

type AdverseEventStatsResponse struct {
	Drug struct {
		Slug string `json:"slug"`
		Name string `json:"name"`
	} `json:"drug"`
	Stats AdverseEventStats `json:"stats"`
}

type LiteratureReference struct {
	Pmid string `json:"pmid"`
	Title string `json:"title"`
	Journal string `json:"journal"`
	Year int `json:"year"`
	Authors []string `json:"authors"`
	Doi *string `json:"doi,omitempty"`
	PubmedUrl string `json:"pubmedUrl"`
}

type DrugLiteratureResponse struct {
	Drug struct {
		Slug string `json:"slug"`
		Name string `json:"name"`
	} `json:"drug"`
	References []LiteratureReference `json:"references"`
	Total int `json:"total"`
}

type TrialEntry struct {
	NctId string `json:"nctId"`
	Title string `json:"title"`
	OverallStatus string `json:"overallStatus"`
	Phases []string `json:"phases"`
	StudyType *string `json:"studyType,omitempty"`
	Conditions []string `json:"conditions"`
	LeadSponsor *string `json:"leadSponsor,omitempty"`
	StartDate *string `json:"startDate,omitempty"`
	LastUpdateDate *string `json:"lastUpdateDate,omitempty"`
	Enrollment *int `json:"enrollment,omitempty"`
	Url string `json:"url"`
}

type DrugTrialsResponse struct {
	Drug struct {
		Slug string `json:"slug"`
		Name string `json:"name"`
	} `json:"drug"`
	Trials []TrialEntry `json:"trials"`
	TotalCount int `json:"totalCount"`
	Sampled int `json:"sampled"`
	Disclaimer string `json:"disclaimer"`
}

type DrugHistoryResponse struct {
	Drug struct {
		Slug string `json:"slug"`
		Name string `json:"name"`
	} `json:"drug"`
	Provenance Provenance `json:"provenance"`
	AsOf *string `json:"asOf,omitempty"`
	Events []ChangelogEntry `json:"events"`
	Total int `json:"total"`
}

type PgxPair struct {
	Gene string `json:"gene"`
	CpicLevel *string `json:"cpicLevel,omitempty"`
	ClinpgxLevel *string `json:"clinpgxLevel,omitempty"`
	FdaLabelTesting *string `json:"fdaLabelTesting,omitempty"`
	GuidelineName *string `json:"guidelineName,omitempty"`
	GuidelineUrl *string `json:"guidelineUrl,omitempty"`
	Citations []string `json:"citations"`
	Provisional bool `json:"provisional"`
}

type DrugPgxResponse struct {
	Drug struct {
		Slug string `json:"slug"`
		Name string `json:"name"`
	} `json:"drug"`
	Pairs []PgxPair `json:"pairs"`
	Total int `json:"total"`
	Disclaimer string `json:"disclaimer"`
}

type ReactionSummary struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
	Aliases []string `json:"aliases"`
	DrugCount int `json:"drugCount"`
	TotalReports int `json:"totalReports"`
}

type ReactionDrugRow struct {
	Drug string `json:"drug"`
	Name string `json:"name"`
	Count int `json:"count"`
	Share float64 `json:"share"`
	DrugTotalReports int `json:"drugTotalReports"`
}

type RelatedReaction struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
	SharedDrugs int `json:"sharedDrugs"`
	Similarity float64 `json:"similarity"`
}

type MeshTreeNode struct {
	Uid string `json:"uid"`
	DescriptorId string `json:"descriptorId"`
	Name string `json:"name"`
}

type ReactionMeta struct {
	MeshDescriptorId string `json:"meshDescriptorId"`
	MeshUid string `json:"meshUid"`
	MeshDescriptorName string `json:"meshDescriptorName"`
	MeshEntryTerms []string `json:"meshEntryTerms"`
	ScopeNote string `json:"scopeNote"`
	TreeNumbers []string `json:"treeNumbers"`
	Parents []MeshTreeNode `json:"parents"`
	MeshBrowserUrl string `json:"meshBrowserUrl"`
	References []LiteratureReference `json:"references"`
	Provenance Provenance `json:"provenance"`
}

type Reaction struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
	Aliases []string `json:"aliases"`
	DrugCount int `json:"drugCount"`
	TotalReports int `json:"totalReports"`
	Drugs []ReactionDrugRow `json:"drugs"`
	RelatedReactions []RelatedReaction `json:"relatedReactions"`
	Meta ReactionMeta `json:"meta"`
	Disclaimer string `json:"disclaimer"`
}

type ReactionsListResponse struct {
	Items []ReactionSummary `json:"items"`
	Pagination Pagination `json:"pagination"`
}

type ReactionResponse struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
	Aliases []string `json:"aliases"`
	DrugCount int `json:"drugCount"`
	TotalReports int `json:"totalReports"`
	Drugs []ReactionDrugRow `json:"drugs"`
	RelatedReactions []RelatedReaction `json:"relatedReactions"`
	Meta ReactionMeta `json:"meta"`
	Disclaimer string `json:"disclaimer"`
}

type ConditionSummary struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
	Icd10 string `json:"icd10"`
	Category string `json:"category"`
	DrugCount int `json:"drugCount"`
}

type ConditionDrugRow struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
	Indications []string `json:"indications"`
}

type RelatedCondition struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
	SharedDrugs int `json:"sharedDrugs"`
	Similarity float64 `json:"similarity"`
}

type Condition struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
	Icd10 string `json:"icd10"`
	Category string `json:"category"`
	DrugCount int `json:"drugCount"`
	Drugs []ConditionDrugRow `json:"drugs"`
	RelatedConditions []RelatedCondition `json:"relatedConditions"`
	Disclaimer string `json:"disclaimer"`
}

type ConditionsListResponse struct {
	Items []ConditionSummary `json:"items"`
	Pagination Pagination `json:"pagination"`
}

type ConditionResponse struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
	Icd10 string `json:"icd10"`
	Category string `json:"category"`
	DrugCount int `json:"drugCount"`
	Drugs []ConditionDrugRow `json:"drugs"`
	RelatedConditions []RelatedCondition `json:"relatedConditions"`
	Disclaimer string `json:"disclaimer"`
}

type PassageSection string

const (
	PassageSectionOverview PassageSection = "overview"
	PassageSectionMechanism PassageSection = "mechanism"
	PassageSectionIndications PassageSection = "indications"
	PassageSectionContraindications PassageSection = "contraindications"
	PassageSectionDosing PassageSection = "dosing"
	PassageSectionPharmacokinetics PassageSection = "pharmacokinetics"
	PassageSectionInteractions PassageSection = "interactions"
	PassageSectionBoxedWarning PassageSection = "boxed-warning"
	PassageSectionDosageAndAdministration PassageSection = "dosage-and-administration"
	PassageSectionWarningsAndPrecautions PassageSection = "warnings-and-precautions"
	PassageSectionAdverseReactions PassageSection = "adverse-reactions"
	PassageSectionUseInSpecificPopulations PassageSection = "use-in-specific-populations"
	PassageSectionOverdosage PassageSection = "overdosage"
	PassageSectionPatientSummary PassageSection = "patient-summary"
)

type RetrievalMethod string

const (
	RetrievalMethodEmbedding RetrievalMethod = "embedding"
	RetrievalMethodLexical RetrievalMethod = "lexical"
)

type SemanticPassage struct {
	Id string `json:"id"`
	Drug struct {
		Slug string `json:"slug"`
		Name string `json:"name"`
	} `json:"drug"`
	Section PassageSection `json:"section"`
	Chunk int `json:"chunk"`
	Text string `json:"text"`
	Score float64 `json:"score"`
	Provenance Provenance `json:"provenance"`
}

type SemanticSearchResponse struct {
	Query string `json:"query"`
	Method RetrievalMethod `json:"method"`
	Model *string `json:"model,omitempty"`
	Results []SemanticPassage `json:"results"`
	Total int `json:"total"`
	Disclaimer string `json:"disclaimer"`
}

type GroundedRequest struct {
	Query string `json:"query"`
	Limit int `json:"limit"`
	Sections []PassageSection `json:"sections,omitempty"`
}

type GroundedCitation struct {
	Id string `json:"id"`
	Drug struct {
		Slug string `json:"slug"`
		Name string `json:"name"`
	} `json:"drug"`
	Section PassageSection `json:"section"`
	PassageId string `json:"passageId"`
	Url string `json:"url"`
	Provenance Provenance `json:"provenance"`
}

type GroundingSpan struct {
	Start int `json:"start"`
	End int `json:"end"`
	CitationId string `json:"citationId"`
}

type GroundedPassage struct {
	Id string `json:"id"`
	CitationId string `json:"citationId"`
	Drug struct {
		Slug string `json:"slug"`
		Name string `json:"name"`
	} `json:"drug"`
	Section PassageSection `json:"section"`
	Chunk int `json:"chunk"`
	Text string `json:"text"`
	Score float64 `json:"score"`
	Grounding []GroundingSpan `json:"grounding"`
}

type GroundedResponse struct {
	Query string `json:"query"`
	Method RetrievalMethod `json:"method"`
	Model *string `json:"model,omitempty"`
	Passages []GroundedPassage `json:"passages"`
	Citations []GroundedCitation `json:"citations"`
	Usage struct {
		Tier string `json:"tier"`
		RequestCount *int `json:"requestCount,omitempty"`
	} `json:"usage"`
	Disclaimer string `json:"disclaimer"`
}

type WebhookEventName string

const (
	WebhookEventNameDrugCreated WebhookEventName = "drug.created"
	WebhookEventNameDrugUpdated WebhookEventName = "drug.updated"
	WebhookEventNameDrugDeleted WebhookEventName = "drug.deleted"
	WebhookEventNameDatasetRefreshed WebhookEventName = "dataset.refreshed"
)

type WebhookDrugChange struct {
	Slug string `json:"slug"`
	Name *string `json:"name,omitempty"`
	SourceHash *string `json:"sourceHash,omitempty"`
	ChangedSections []string `json:"changedSections,omitempty"`
}

type WebhookEventPayload struct {
	Id string `json:"id"`
	Event WebhookEventName `json:"event"`
	Timestamp string `json:"timestamp"`
	DatasetVersion *string `json:"datasetVersion,omitempty"`
	Drugs []WebhookDrugChange `json:"drugs,omitempty"`
	Summary *struct {
		Created int `json:"created"`
		Updated int `json:"updated"`
		Deleted int `json:"deleted"`
	} `json:"summary,omitempty"`
}

type WebhookEndpoint struct {
	Id string `json:"id"`
	Url string `json:"url"`
	Events []WebhookEventName `json:"events"`
	Active bool `json:"active"`
	CreatedAt string `json:"createdAt"`
	FailureCount int `json:"failureCount"`
	LastStatus *int `json:"lastStatus,omitempty"`
	LastDeliveryAt *string `json:"lastDeliveryAt,omitempty"`
}

type WebhookCreateRequest struct {
	Url string `json:"url"`
	Events []WebhookEventName `json:"events"`
}

type WebhookEndpointCreated struct {
	Id string `json:"id"`
	Url string `json:"url"`
	Events []WebhookEventName `json:"events"`
	Active bool `json:"active"`
	CreatedAt string `json:"createdAt"`
	FailureCount int `json:"failureCount"`
	LastStatus *int `json:"lastStatus,omitempty"`
	LastDeliveryAt *string `json:"lastDeliveryAt,omitempty"`
	Secret string `json:"secret"`
}

type WebhooksListResponse struct {
	Endpoints []WebhookEndpoint `json:"endpoints"`
	Total int `json:"total"`
}

type WebhookDeleteResponse struct {
	Deleted string `json:"deleted"`
	Id string `json:"id"`
}
