# AUTO-GENERATED by `npm run codegen`. Do not edit by hand.
# Source of truth: lib/schemas/*.ts + lib/sdk/manifest.ts
from __future__ import annotations

from typing import Any, Dict, Optional
from urllib.parse import quote

from .models import (
    BrandsResponse,
    ChangelogResponse,
    ClassDetailResponse,
    ClassListResponse,
    Drug,
    DrugInteractionsResponse,
    DrugListResponse,
    HealthResponse,
    Ingredient,
    IngredientListResponse,
    InteractionCheckRequest,
    InteractionCheckResponse,
    SearchResponse,
    SimilarDrugsResponse,
    Stats,
    StructureSearchRequest,
    StructureSearchResponse,
)

DEFAULT_BASE_URL = "https://pharmacopeia.dev/api/v1"


def _drop_none(values: Dict[str, Any]) -> Dict[str, Any]:
    return {k: v for k, v in values.items() if v is not None}


class PharmacopeiaError(Exception):
    """Raised when the API returns a non-2xx response."""

    def __init__(
        self,
        message: str,
        *,
        code: Optional[str] = None,
        status: int = 0,
        details: Any = None,
    ) -> None:
        super().__init__(message)
        self.code = code
        self.status = status
        self.details = details


class PharmacopeiaClient:
    """Thin, fully-typed client for the pharmacopeia API.

    Each method returns a Pydantic model matching the API response; non-2xx
    responses raise :class:`PharmacopeiaError` carrying the API error code
    and details. Usable as a context manager to close the underlying
    connection pool.
    """

    def __init__(
        self,
        base_url: str = DEFAULT_BASE_URL,
        *,
        api_key: Optional[str] = None,
        timeout: float = 30.0,
        headers: Optional[Dict[str, str]] = None,
    ) -> None:
        import httpx

        merged: Dict[str, str] = {"Accept": "application/json"}
        if api_key:
            merged["Authorization"] = f"Bearer {api_key}"
        if headers:
            merged.update(headers)

        self._client = httpx.Client(
            base_url=base_url.rstrip("/") + "/",
            headers=merged,
            timeout=timeout,
        )

    def close(self) -> None:
        self._client.close()

    def __enter__(self) -> "PharmacopeiaClient":
        return self

    def __exit__(self, *_exc: Any) -> None:
        self.close()

    def _request(
        self,
        method: str,
        path: str,
        *,
        params: Optional[Dict[str, Any]] = None,
        json_body: Any = None,
    ) -> Any:
        response = self._client.request(
            method,
            path.lstrip("/"),
            params=params,
            json=json_body,
        )
        if response.status_code >= 400:
            payload: Any = None
            try:
                payload = response.json()
            except ValueError:
                payload = None
            error = (payload or {}).get("error", {}) if isinstance(payload, dict) else {}
            raise PharmacopeiaError(
                error.get("message", response.reason_phrase),
                code=error.get("code"),
                status=response.status_code,
                details=error.get("details"),
            )
        return response.json()

    def list_drugs(self, *, limit: Optional[int] = None, offset: Optional[int] = None, drug_class: Optional[str] = None, ingredient: Optional[str] = None) -> DrugListResponse:
        """List drugs (paginated), optionally filtered by class or ingredient."""
        params = _drop_none({"limit": limit, "offset": offset, "class": drug_class, "ingredient": ingredient})
        data = self._request("GET", "/drugs", params=params)
        return DrugListResponse.model_validate(data)

    def get_drug(self, slug: str) -> Drug:
        """Fetch a single drug by slug."""
        data = self._request("GET", f"/drug/{quote(str(slug), safe='')}")
        return Drug.model_validate(data)

    def get_drug_interactions(self, slug: str) -> DrugInteractionsResponse:
        """List known interactions for a drug."""
        data = self._request("GET", f"/drug/{quote(str(slug), safe='')}/interactions")
        return DrugInteractionsResponse.model_validate(data)

    def get_similar_drugs(self, slug: str) -> SimilarDrugsResponse:
        """Structurally similar drugs (Tanimoto over 2D fingerprints)."""
        data = self._request("GET", f"/drug/{quote(str(slug), safe='')}/similar")
        return SimilarDrugsResponse.model_validate(data)

    def list_classes(self, *, limit: Optional[int] = None, offset: Optional[int] = None) -> ClassListResponse:
        """List drug classes (paginated)."""
        params = _drop_none({"limit": limit, "offset": offset})
        data = self._request("GET", "/classes", params=params)
        return ClassListResponse.model_validate(data)

    def get_class(self, slug: str) -> ClassDetailResponse:
        """Fetch a single drug class plus the drugs it contains."""
        data = self._request("GET", f"/class/{quote(str(slug), safe='')}")
        return ClassDetailResponse.model_validate(data)

    def list_ingredients(self, *, limit: Optional[int] = None, offset: Optional[int] = None) -> IngredientListResponse:
        """List active ingredients (paginated)."""
        params = _drop_none({"limit": limit, "offset": offset})
        data = self._request("GET", "/ingredients", params=params)
        return IngredientListResponse.model_validate(data)

    def get_ingredient(self, slug: str) -> Ingredient:
        """Fetch a single ingredient by slug."""
        data = self._request("GET", f"/ingredient/{quote(str(slug), safe='')}")
        return Ingredient.model_validate(data)

    def list_brands(self) -> BrandsResponse:
        """Brand → generic crosswalk for every brand in the dataset."""
        data = self._request("GET", "/brands")
        return BrandsResponse.model_validate(data)

    def get_stats(self) -> Stats:
        """Dataset counts and version metadata."""
        data = self._request("GET", "/stats")
        return Stats.model_validate(data)

    def get_health(self) -> HealthResponse:
        """Liveness + dataset-version probe. Tiny payload for monitors and clients."""
        data = self._request("GET", "/health")
        return HealthResponse.model_validate(data)

    def search(self, *, q: str, limit: Optional[int] = None) -> SearchResponse:
        """Full-text search across drugs, classes, and ingredients."""
        params = _drop_none({"q": q, "limit": limit})
        data = self._request("GET", "/search", params=params)
        return SearchResponse.model_validate(data)

    def check_interactions(self, body: InteractionCheckRequest) -> InteractionCheckResponse:
        """Check a set of 2–20 drug slugs for pairwise interactions."""
        data = self._request("POST", "/interactions/check", json_body=body.model_dump(by_alias=True, exclude_none=True))
        return InteractionCheckResponse.model_validate(data)

    def structure_search(self, body: StructureSearchRequest) -> StructureSearchResponse:
        """Rank drugs in the dataset by 2D Tanimoto similarity to a caller-supplied SMILES. Structural proximity only."""
        data = self._request("POST", "/structure-search", json_body=body.model_dump(by_alias=True, exclude_none=True))
        return StructureSearchResponse.model_validate(data)

    def list_changelog(self, *, limit: Optional[int] = None, since: Optional[str] = None) -> ChangelogResponse:
        """Recent record-level changes (typed mirror of /feed.xml and /feed.json)."""
        params = _drop_none({"limit": limit, "since": since})
        data = self._request("GET", "/changelog", params=params)
        return ChangelogResponse.model_validate(data)
