# AUTO-GENERATED by `npm run codegen`. Do not edit by hand.
# Source of truth: lib/schemas/*.ts + lib/sdk/manifest.ts
from __future__ import annotations

from typing import Any, Dict, Optional
from urllib.parse import quote

from .models import (
    AdverseEventStatsResponse,
    BrandsResponse,
    ChangelogResponse,
    ClassDetailResponse,
    ClassListResponse,
    Drug,
    DrugInteractionsResponse,
    DrugListResponse,
    DrugLiteratureResponse,
    DrugShortagesResponse,
    DrugsBatchRequest,
    DrugsBatchResponse,
    GroundedRequest,
    GroundedResponse,
    HealthResponse,
    Ingredient,
    IngredientListResponse,
    InteractionCheckRequest,
    InteractionCheckResponse,
    ReactionResponse,
    ReactionsListResponse,
    SearchResponse,
    SemanticSearchResponse,
    ShortagesResponse,
    SimilarDrugsResponse,
    Stats,
    StructureSearchRequest,
    StructureSearchResponse,
    WebhookCreateRequest,
    WebhookDeleteResponse,
    WebhookEndpointCreated,
    WebhooksListResponse,
)

DEFAULT_BASE_URL = "https://pharmacopeia.dev/api/v1"


def _drop_none(values: Dict[str, Any]) -> Dict[str, Any]:
    return {k: v for k, v in values.items() if v is not None}


class PharmacopeiaError(Exception):
    """Raised when the API returns a non-2xx response."""

    def __init__(
        self,
        message: str,
        *,
        code: Optional[str] = None,
        status: int = 0,
        details: Any = None,
    ) -> None:
        super().__init__(message)
        self.code = code
        self.status = status
        self.details = details


class PharmacopeiaClient:
    """Thin, fully-typed client for the pharmacopeia API.

    Each method returns a Pydantic model matching the API response; non-2xx
    responses raise :class:`PharmacopeiaError` carrying the API error code
    and details. Usable as a context manager to close the underlying
    connection pool.
    """

    def __init__(
        self,
        base_url: str = DEFAULT_BASE_URL,
        *,
        api_key: Optional[str] = None,
        timeout: float = 30.0,
        headers: Optional[Dict[str, str]] = None,
    ) -> None:
        import httpx

        merged: Dict[str, str] = {"Accept": "application/json"}
        if api_key:
            merged["Authorization"] = f"Bearer {api_key}"
        if headers:
            merged.update(headers)

        self._client = httpx.Client(
            base_url=base_url.rstrip("/") + "/",
            headers=merged,
            timeout=timeout,
        )

    def close(self) -> None:
        self._client.close()

    def __enter__(self) -> "PharmacopeiaClient":
        return self

    def __exit__(self, *_exc: Any) -> None:
        self.close()

    def _request(
        self,
        method: str,
        path: str,
        *,
        params: Optional[Dict[str, Any]] = None,
        json_body: Any = None,
    ) -> Any:
        response = self._client.request(
            method,
            path.lstrip("/"),
            params=params,
            json=json_body,
        )
        if response.status_code >= 400:
            payload: Any = None
            try:
                payload = response.json()
            except ValueError:
                payload = None
            error = (payload or {}).get("error", {}) if isinstance(payload, dict) else {}
            raise PharmacopeiaError(
                error.get("message", response.reason_phrase),
                code=error.get("code"),
                status=response.status_code,
                details=error.get("details"),
            )
        return response.json()

    def list_drugs(self, *, limit: Optional[int] = None, offset: Optional[int] = None, drug_class: Optional[str] = None, ingredient: Optional[str] = None) -> DrugListResponse:
        """List drugs (paginated), optionally filtered by class or ingredient."""
        params = _drop_none({"limit": limit, "offset": offset, "class": drug_class, "ingredient": ingredient})
        data = self._request("GET", "/drugs", params=params)
        return DrugListResponse.model_validate(data)

    def get_drug(self, slug: str, *, fields: Optional[str] = None) -> Drug:
        """Fetch a single drug by slug."""
        params = _drop_none({"fields": fields})
        data = self._request("GET", f"/drug/{quote(str(slug), safe='')}", params=params)
        return Drug.model_validate(data)

    def get_drugs_batch(self, body: DrugsBatchRequest) -> DrugsBatchResponse:
        """Fetch up to 100 drug records in a single round-trip. Returns the full records found plus the slugs that did not resolve."""
        data = self._request("POST", "/drugs/batch", json_body=body.model_dump(by_alias=True, exclude_none=True))
        return DrugsBatchResponse.model_validate(data)

    def get_drug_interactions(self, slug: str) -> DrugInteractionsResponse:
        """List known interactions for a drug."""
        data = self._request("GET", f"/drug/{quote(str(slug), safe='')}/interactions")
        return DrugInteractionsResponse.model_validate(data)

    def get_similar_drugs(self, slug: str) -> SimilarDrugsResponse:
        """Structurally similar drugs (Tanimoto over 2D fingerprints)."""
        data = self._request("GET", f"/drug/{quote(str(slug), safe='')}/similar")
        return SimilarDrugsResponse.model_validate(data)

    def list_classes(self, *, limit: Optional[int] = None, offset: Optional[int] = None) -> ClassListResponse:
        """List drug classes (paginated)."""
        params = _drop_none({"limit": limit, "offset": offset})
        data = self._request("GET", "/classes", params=params)
        return ClassListResponse.model_validate(data)

    def get_class(self, slug: str) -> ClassDetailResponse:
        """Fetch a single drug class plus the drugs it contains."""
        data = self._request("GET", f"/class/{quote(str(slug), safe='')}")
        return ClassDetailResponse.model_validate(data)

    def list_ingredients(self, *, limit: Optional[int] = None, offset: Optional[int] = None) -> IngredientListResponse:
        """List active ingredients (paginated)."""
        params = _drop_none({"limit": limit, "offset": offset})
        data = self._request("GET", "/ingredients", params=params)
        return IngredientListResponse.model_validate(data)

    def get_ingredient(self, slug: str) -> Ingredient:
        """Fetch a single ingredient by slug."""
        data = self._request("GET", f"/ingredient/{quote(str(slug), safe='')}")
        return Ingredient.model_validate(data)

    def list_brands(self) -> BrandsResponse:
        """Brand → generic crosswalk for every brand in the dataset."""
        data = self._request("GET", "/brands")
        return BrandsResponse.model_validate(data)

    def get_stats(self) -> Stats:
        """Dataset counts and version metadata."""
        data = self._request("GET", "/stats")
        return Stats.model_validate(data)

    def get_health(self) -> HealthResponse:
        """Liveness + dataset-version probe. Tiny payload for monitors and clients."""
        data = self._request("GET", "/health")
        return HealthResponse.model_validate(data)

    def search(self, *, q: str, limit: Optional[int] = None) -> SearchResponse:
        """Full-text search across drugs, classes, and ingredients."""
        params = _drop_none({"q": q, "limit": limit})
        data = self._request("GET", "/search", params=params)
        return SearchResponse.model_validate(data)

    def check_interactions(self, body: InteractionCheckRequest) -> InteractionCheckResponse:
        """Check a set of 2–20 drug slugs for pairwise interactions."""
        data = self._request("POST", "/interactions/check", json_body=body.model_dump(by_alias=True, exclude_none=True))
        return InteractionCheckResponse.model_validate(data)

    def structure_search(self, body: StructureSearchRequest) -> StructureSearchResponse:
        """Rank drugs in the dataset by 2D Tanimoto similarity to a caller-supplied SMILES. Structural proximity only."""
        data = self._request("POST", "/structure-search", json_body=body.model_dump(by_alias=True, exclude_none=True))
        return StructureSearchResponse.model_validate(data)

    def get_drug_shortages(self, slug: str) -> DrugShortagesResponse:
        """FDA shortage entries (active, resolved, discontinuation) for a drug. Reference statistics only."""
        data = self._request("GET", f"/drug/{quote(str(slug), safe='')}/shortages")
        return DrugShortagesResponse.model_validate(data)

    def list_shortages(self) -> ShortagesResponse:
        """Every shortage entry across the dataset, sorted by drug then presentation."""
        data = self._request("GET", "/shortages")
        return ShortagesResponse.model_validate(data)

    def get_drug_adverse_events(self, slug: str) -> AdverseEventStatsResponse:
        """Aggregate FAERS report counts for a drug — top reactions by reporting volume. NOT incidence rates, signals, or causality."""
        data = self._request("GET", f"/drug/{quote(str(slug), safe='')}/adverse-events")
        return AdverseEventStatsResponse.model_validate(data)

    def get_drug_literature(self, slug: str) -> DrugLiteratureResponse:
        """Curated PubMed references for a drug, pinned to MeSH major topic at ingest time."""
        data = self._request("GET", f"/drug/{quote(str(slug), safe='')}/literature")
        return DrugLiteratureResponse.model_validate(data)

    def list_reactions(self, *, limit: Optional[int] = None, offset: Optional[int] = None) -> ReactionsListResponse:
        """Browse MedDRA Preferred Terms reported to FAERS across the dataset, ordered by total reporting volume. Reference statistics only — NOT a symptom checker."""
        params = _drop_none({"limit": limit, "offset": offset})
        data = self._request("GET", "/reactions", params=params)
        return ReactionsListResponse.model_validate(data)

    def get_reaction(self, slug: str) -> ReactionResponse:
        """Fetch one MedDRA Preferred Term with its per-drug breakdown (count + share of matched FAERS reports), related reactions ranked by Jaccard similarity over the drug-id sets, and optional reference metadata — NLM MeSH descriptor id, scope note, tree position, and recent PubMed papers on the term as a MeSH major topic. Alias slugs 301-redirect to canonical."""
        data = self._request("GET", f"/reaction/{quote(str(slug), safe='')}")
        return ReactionResponse.model_validate(data)

    def semantic_search(self, *, q: str, limit: Optional[int] = None, sections: Optional[str] = None) -> SemanticSearchResponse:
        """Meaning-based retrieval over drug-record passages. Embedding-backed when available; lexical fallback otherwise — `method` in the response reports which."""
        params = _drop_none({"q": q, "limit": limit, "sections": sections})
        data = self._request("GET", "/semantic-search", params=params)
        return SemanticSearchResponse.model_validate(data)

    def grounded_retrieval(self, body: GroundedRequest) -> GroundedResponse:
        """Key-gated retrieval tier for LLM consumers: same passages as /semantic-search plus per-span citations carrying full provenance (source URL, content hash, extraction timestamp, confidence)."""
        data = self._request("POST", "/grounded", json_body=body.model_dump(by_alias=True, exclude_none=True))
        return GroundedResponse.model_validate(data)

    def list_webhooks(self) -> WebhooksListResponse:
        """List the webhook endpoints registered by the calling API key."""
        data = self._request("GET", "/webhooks")
        return WebhooksListResponse.model_validate(data)

    def create_webhook(self, body: WebhookCreateRequest) -> WebhookEndpointCreated:
        """Register a webhook endpoint. The response includes the HMAC signing secret exactly once — store it."""
        data = self._request("POST", "/webhooks", json_body=body.model_dump(by_alias=True, exclude_none=True))
        return WebhookEndpointCreated.model_validate(data)

    def delete_webhook(self, id: str) -> WebhookDeleteResponse:
        """Delete a webhook endpoint owned by the calling API key."""
        data = self._request("DELETE", f"/webhooks/{quote(str(id), safe='')}")
        return WebhookDeleteResponse.model_validate(data)

    def list_changelog(self, *, limit: Optional[int] = None, since: Optional[str] = None) -> ChangelogResponse:
        """Recent record-level changes (typed mirror of /feed.xml and /feed.json)."""
        params = _drop_none({"limit": limit, "since": since})
        data = self._request("GET", "/changelog", params=params)
        return ChangelogResponse.model_validate(data)
