# AUTO-GENERATED by `npm run codegen`. Do not edit by hand.
# Source of truth: lib/schemas/*.ts + lib/sdk/manifest.ts
from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field

Jurisdiction = Literal["US-FDA", "EU-EMA", "UK-MHRA", "CA-HC"]


Severity = Literal["contraindicated", "major", "moderate", "minor", "unknown"]


DrugClassKind = Literal["atc", "moa", "epc", "pe", "pharm", "mesh"]


class Provenance(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    source_url: str = Field(alias="sourceUrl")
    source_hash: str = Field(alias="sourceHash")
    extracted_at: str = Field(alias="extractedAt")
    extractor: str
    confidence: float


class Pagination(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    total: int
    limit: int
    offset: int


class ApiError(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    error: Dict[str, Any]


class DrugRef(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    slug: str
    name: str


class Indication(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    text: str
    icd10: List[str]
    snomed: List[str]


class Contraindication(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    text: str
    severity: Severity


class Dosing(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    route: Literal["oral", "iv", "im", "subcutaneous", "topical", "inhaled", "intranasal", "rectal", "ophthalmic", "otic", "transdermal", "other"]
    population: Literal["adult", "pediatric", "geriatric", "renal-impairment", "hepatic-impairment", "pregnancy"]
    condition: Optional[str] = None
    dose: str
    frequency: Optional[str] = None
    max_dose: Optional[str] = Field(default=None, alias="maxDose")
    notes: Optional[str] = None


class Pharmacokinetics(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    half_life: Optional[str] = Field(default=None, alias="halfLife")
    t_max: Optional[str] = Field(default=None, alias="tMax")
    bioavailability: Optional[str] = None
    protein_binding: Optional[str] = Field(default=None, alias="proteinBinding")
    metabolism: Optional[str] = None
    excretion: Optional[str] = None


class Mechanism(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    summary: str
    targets: List[str]


class Approval(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    date: str
    application_number: str = Field(alias="applicationNumber")
    type: Literal["NDA", "ANDA", "BLA", "OTC"]
    sponsor: Optional[str] = None


class LabelSections(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    boxed_warning: Optional[str] = Field(default=None, alias="boxedWarning")
    dosage_and_administration: Optional[str] = Field(default=None, alias="dosageAndAdministration")
    warnings_and_precautions: Optional[str] = Field(default=None, alias="warningsAndPrecautions")
    adverse_reactions: Optional[str] = Field(default=None, alias="adverseReactions")
    use_in_specific_populations: Optional[str] = Field(default=None, alias="useInSpecificPopulations")
    overdosage: Optional[str] = None


class Identifier(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    rxcui: Optional[str] = None
    ndc: List[str]
    atc: List[str]
    drugbank: Optional[str] = None
    chembl: Optional[str] = None
    pubchem: Optional[str] = None
    unii: Optional[str] = None


class ChemicalStructure(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    smiles: str
    inchi_key: Optional[str] = Field(default=None, alias="inchiKey")
    iupac_name: Optional[str] = Field(default=None, alias="iupacName")
    pubchem_cid: Optional[int] = Field(default=None, alias="pubchemCid")
    structure_svg_path: str = Field(alias="structureSvgPath")
    provenance: Provenance


class DrugClassRef(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    slug: str
    name: str
    kind: DrugClassKind
    code: Optional[str] = None


class DrugClassParent(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    slug: str
    name: str


class DrugClass(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    slug: str
    name: str
    kind: DrugClassKind
    code: Optional[str] = None
    description: Optional[str] = None
    parent: Optional[DrugClassParent] = None
    drug_count: int = Field(alias="drugCount")
    provenance: Provenance


class IngredientRef(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    slug: str
    name: str
    strength: Optional[str] = None


class Ingredient(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    slug: str
    name: str
    synonyms: List[str]
    rxcui: Optional[str] = None
    unii: Optional[str] = None
    smiles: Optional[str] = None
    inchikey: Optional[str] = None
    molecular_formula: Optional[str] = Field(default=None, alias="molecularFormula")
    molecular_weight: Optional[float] = Field(default=None, alias="molecularWeight")
    drug_count: int = Field(alias="drugCount")
    provenance: Provenance


class DrugSummary(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    slug: str
    name: str
    synonyms: List[str]
    jurisdiction: Jurisdiction
    ingredients: List[IngredientRef]
    brands: List[str]
    classes: List[DrugClassRef]
    short_description: Optional[str] = Field(default=None, alias="shortDescription")


class Drug(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    slug: str
    name: str
    synonyms: List[str]
    jurisdiction: Jurisdiction
    ingredients: List[IngredientRef]
    brands: List[str]
    classes: List[DrugClassRef]
    short_description: Optional[str] = Field(default=None, alias="shortDescription")
    mechanism: Optional[Mechanism] = None
    indications: List[Indication]
    contraindications: List[Contraindication]
    dosing: List[Dosing]
    pharmacokinetics: Optional[Pharmacokinetics] = None
    approval_history: List[Approval] = Field(alias="approvalHistory")
    patient_summary: Optional[str] = Field(default=None, alias="patientSummary")
    interactions_narrative: Optional[str] = Field(default=None, alias="interactionsNarrative")
    label_sections: Optional[LabelSections] = Field(default=None, alias="labelSections")
    identifiers: Identifier
    chemical: Optional[ChemicalStructure] = None
    provenance: Provenance


class DrugsBatchRequest(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    slugs: List[str]


class DrugsBatchResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    found: List[Drug]
    missing: List[str]
    total: int


class Interaction(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    drug_a: str = Field(alias="drugA")
    drug_b: str = Field(alias="drugB")
    severity: Severity
    mechanism: Optional[str] = None
    description: str
    recommendation: Optional[str] = None
    evidence_span: Optional[str] = Field(default=None, alias="evidenceSpan")
    provenance: Provenance


class InteractionSummary(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    contraindicated: int
    major: int
    moderate: int
    minor: int
    unknown: int


class InteractionCheckRequest(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    drugs: List[str]


class InteractionCheckResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    input: List[str]
    pairs: List[Interaction]
    summary: InteractionSummary


class Stats(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    drugs: int
    classes: int
    ingredients: int
    interactions: int
    indications: int
    version: str
    updated_at: str = Field(alias="updatedAt")


class HealthResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    status: Literal["ok"]
    version: str
    updated_at: str = Field(alias="updatedAt")
    time: str
    uptime: Optional[int] = None
    repository: Literal["static", "supabase"]
    commit: Optional[str] = None
    region: Optional[str] = None


class SimilarDrugResult(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    slug: str
    name: str
    score: float
    class_name: Optional[str] = Field(default=None, alias="className")


class BrandEntry(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    brand: str
    drugs: List[DrugRef]


class SearchResult(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    slug: str
    name: str
    kind: Literal["drug", "ingredient", "class"]
    description: Optional[str] = None


class DrugListResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    items: List[DrugSummary]
    pagination: Pagination


class ClassListResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    items: List[DrugClass]
    pagination: Pagination


class IngredientListResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    items: List[Ingredient]
    pagination: Pagination


class DrugInteractionsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    drug: DrugRef
    interactions: List[Interaction]
    total: int


class SimilarDrugsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    drug: DrugRef
    method: Literal["tanimoto-2d-fingerprint"]
    similar: List[SimilarDrugResult]
    total: int


class ClassDetailResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    slug: str
    name: str
    kind: DrugClassKind
    code: Optional[str] = None
    description: Optional[str] = None
    parent: Optional[DrugClassParent] = None
    drug_count: int = Field(alias="drugCount")
    provenance: Provenance
    drugs: List[DrugSummary]


class BrandsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    brands: List[BrandEntry]
    total: int


class SearchResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    query: str
    results: List[SearchResult]
    total: int


class StructureMatch(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    slug: str
    name: str
    score: float
    class_name: Optional[str] = Field(default=None, alias="className")
    smiles: str


class StructureSearchRequest(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    smiles: str
    limit: int
    threshold: float


class StructureSearchResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    query: Dict[str, Any]
    method: Literal["tanimoto-2d-fingerprint"]
    total: int
    results: List[StructureMatch]


ChangelogKind = Literal["drug", "class", "ingredient", "interaction", "structure", "dataset", "endpoint"]


ChangelogAction = Literal["added", "updated", "removed", "released"]


class ChangelogEntry(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    kind: ChangelogKind
    action: ChangelogAction
    entity_slug: Optional[str] = Field(default=None, alias="entitySlug")
    title: str
    summary: str
    timestamp: str
    url: str
    sources: List[str]
    tags: List[str]


class ChangelogResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    entries: List[ChangelogEntry]
    total: int


ShortageStatus = Literal["active", "resolved", "discontinuation", "to-be-discontinued"]


class ShortageEntry(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    drug: str
    status: ShortageStatus
    presentation: str
    sponsor: Optional[str] = None
    reason: Optional[str] = None
    therapeutic_category: Optional[str] = Field(default=None, alias="therapeuticCategory")
    fda_updated_at: str = Field(alias="fdaUpdatedAt")
    provenance: Provenance


class DrugShortagesResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    drug: Dict[str, Any]
    entries: List[ShortageEntry]
    any_active: bool = Field(alias="anyActive")
    total: int


class ShortagesResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    entries: List[ShortageEntry]
    total: int


class AdverseEventReport(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    reaction: str
    count: int


class AdverseEventStats(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    drug: str
    total_reports: int = Field(alias="totalReports")
    top_reactions: List[AdverseEventReport] = Field(alias="topReactions")
    window_start: Optional[str] = Field(default=None, alias="windowStart")
    window_end: Optional[str] = Field(default=None, alias="windowEnd")
    disclaimer: str
    provenance: Provenance


class AdverseEventStatsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    drug: Dict[str, Any]
    stats: Optional[AdverseEventStats]


class LiteratureReference(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    pmid: str
    title: str
    journal: str
    year: int
    authors: List[str]
    doi: Optional[str] = None
    pubmed_url: str = Field(alias="pubmedUrl")


class DrugLiteratureResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    drug: Dict[str, Any]
    references: List[LiteratureReference]
    total: int


class TrialEntry(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    nct_id: str = Field(alias="nctId")
    title: str
    overall_status: str = Field(alias="overallStatus")
    phases: List[str]
    study_type: Optional[str] = Field(default=None, alias="studyType")
    conditions: List[str]
    lead_sponsor: Optional[str] = Field(default=None, alias="leadSponsor")
    start_date: Optional[str] = Field(default=None, alias="startDate")
    last_update_date: Optional[str] = Field(default=None, alias="lastUpdateDate")
    enrollment: Optional[int] = None
    url: str


class DrugTrialsResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    drug: Dict[str, Any]
    trials: List[TrialEntry]
    total_count: int = Field(alias="totalCount")
    sampled: int
    disclaimer: str


class PgxPair(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    gene: str
    cpic_level: Optional[str] = Field(default=None, alias="cpicLevel")
    clinpgx_level: Optional[str] = Field(default=None, alias="clinpgxLevel")
    fda_label_testing: Optional[str] = Field(default=None, alias="fdaLabelTesting")
    guideline_name: Optional[str] = Field(default=None, alias="guidelineName")
    guideline_url: Optional[str] = Field(default=None, alias="guidelineUrl")
    citations: List[str]
    provisional: bool


class DrugPgxResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    drug: Dict[str, Any]
    pairs: List[PgxPair]
    total: int
    disclaimer: str


class ReactionSummary(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    slug: str
    name: str
    aliases: List[str]
    drug_count: int = Field(alias="drugCount")
    total_reports: int = Field(alias="totalReports")


class ReactionDrugRow(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    drug: str
    name: str
    count: int
    share: Optional[float]
    drug_total_reports: int = Field(alias="drugTotalReports")


class RelatedReaction(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    slug: str
    name: str
    shared_drugs: int = Field(alias="sharedDrugs")
    similarity: float


class MeshTreeNode(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    uid: str
    descriptor_id: str = Field(alias="descriptorId")
    name: str


class ReactionMeta(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    mesh_descriptor_id: str = Field(alias="meshDescriptorId")
    mesh_uid: str = Field(alias="meshUid")
    mesh_descriptor_name: str = Field(alias="meshDescriptorName")
    mesh_entry_terms: List[str] = Field(alias="meshEntryTerms")
    scope_note: str = Field(alias="scopeNote")
    tree_numbers: List[str] = Field(alias="treeNumbers")
    parents: List[MeshTreeNode]
    mesh_browser_url: str = Field(alias="meshBrowserUrl")
    references: List[LiteratureReference]
    provenance: Provenance


class Reaction(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    slug: str
    name: str
    aliases: List[str]
    drug_count: int = Field(alias="drugCount")
    total_reports: int = Field(alias="totalReports")
    drugs: List[ReactionDrugRow]
    related_reactions: List[RelatedReaction] = Field(alias="relatedReactions")
    meta: Optional[ReactionMeta]
    disclaimer: str


class ReactionsListResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    items: List[ReactionSummary]
    pagination: Pagination


class ReactionResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    slug: str
    name: str
    aliases: List[str]
    drug_count: int = Field(alias="drugCount")
    total_reports: int = Field(alias="totalReports")
    drugs: List[ReactionDrugRow]
    related_reactions: List[RelatedReaction] = Field(alias="relatedReactions")
    meta: Optional[ReactionMeta]
    disclaimer: str


PassageSection = Literal["overview", "mechanism", "indications", "contraindications", "dosing", "pharmacokinetics", "interactions", "boxed-warning", "dosage-and-administration", "warnings-and-precautions", "adverse-reactions", "use-in-specific-populations", "overdosage", "patient-summary"]


RetrievalMethod = Literal["embedding", "lexical"]


class SemanticPassage(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    drug: Dict[str, Any]
    section: PassageSection
    chunk: int
    text: str
    score: float
    provenance: Provenance


class SemanticSearchResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    query: str
    method: RetrievalMethod
    model: Optional[str] = None
    results: List[SemanticPassage]
    total: int
    disclaimer: str


class GroundedRequest(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    query: str
    limit: int
    sections: Optional[List[PassageSection]] = None


class GroundedCitation(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    drug: Dict[str, Any]
    section: PassageSection
    passage_id: str = Field(alias="passageId")
    url: str
    provenance: Provenance


class GroundingSpan(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    start: int
    end: int
    citation_id: str = Field(alias="citationId")


class GroundedPassage(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    citation_id: str = Field(alias="citationId")
    drug: Dict[str, Any]
    section: PassageSection
    chunk: int
    text: str
    score: float
    grounding: List[GroundingSpan]


class GroundedResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    query: str
    method: RetrievalMethod
    model: Optional[str] = None
    passages: List[GroundedPassage]
    citations: List[GroundedCitation]
    usage: Dict[str, Any]
    disclaimer: str


WebhookEventName = Literal["drug.created", "drug.updated", "drug.deleted", "dataset.refreshed"]


class WebhookDrugChange(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    slug: str
    name: Optional[str] = None
    source_hash: Optional[str] = Field(default=None, alias="sourceHash")
    changed_sections: Optional[List[str]] = Field(default=None, alias="changedSections")


class WebhookEventPayload(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    event: WebhookEventName
    timestamp: str
    dataset_version: Optional[str] = Field(default=None, alias="datasetVersion")
    drugs: Optional[List[WebhookDrugChange]] = None
    summary: Optional[Dict[str, Any]] = None


class WebhookEndpoint(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    url: str
    events: List[WebhookEventName]
    active: bool
    created_at: str = Field(alias="createdAt")
    failure_count: int = Field(alias="failureCount")
    last_status: Optional[int] = Field(default=None, alias="lastStatus")
    last_delivery_at: Optional[str] = Field(default=None, alias="lastDeliveryAt")


class WebhookCreateRequest(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    url: str
    events: List[WebhookEventName]


class WebhookEndpointCreated(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    id: str
    url: str
    events: List[WebhookEventName]
    active: bool
    created_at: str = Field(alias="createdAt")
    failure_count: int = Field(alias="failureCount")
    last_status: Optional[int] = Field(default=None, alias="lastStatus")
    last_delivery_at: Optional[str] = Field(default=None, alias="lastDeliveryAt")
    secret: str


class WebhooksListResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    endpoints: List[WebhookEndpoint]
    total: int


class WebhookDeleteResponse(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    deleted: Literal[true]
    id: str
