// AUTO-GENERATED by `npm run codegen`. Do not edit by hand.
// Source of truth: lib/schemas/*.ts + lib/sdk/manifest.ts

import type {
  AdverseEventStatsResponse,
  BrandsResponse,
  ChangelogResponse,
  ClassDetailResponse,
  ClassListResponse,
  Drug,
  DrugInteractionsResponse,
  DrugListResponse,
  DrugLiteratureResponse,
  DrugShortagesResponse,
  DrugsBatchRequest,
  DrugsBatchResponse,
  GroundedRequest,
  GroundedResponse,
  HealthResponse,
  Ingredient,
  IngredientListResponse,
  InteractionCheckRequest,
  InteractionCheckResponse,
  ReactionResponse,
  ReactionsListResponse,
  SearchResponse,
  SemanticSearchResponse,
  ShortagesResponse,
  SimilarDrugsResponse,
  Stats,
  StructureSearchRequest,
  StructureSearchResponse,
  WebhookCreateRequest,
  WebhookDeleteResponse,
  WebhookEndpointCreated,
  WebhooksListResponse,
} from "./types";

/** Base URL of the pharmacopeia API (origin + `/api/v1`). */
export const DEFAULT_BASE_URL = "https://pharmacopeia.dev/api/v1";

export interface PharmacopeiaClientOptions {
  /** Override the API base URL. Defaults to `DEFAULT_BASE_URL`. */
  baseUrl?: string;
  /** Custom fetch implementation (defaults to the global `fetch`). */
  fetch?: typeof fetch;
  /** Extra headers sent on every request. */
  headers?: Record<string, string>;
  /** Optional bearer token, sent as `Authorization: Bearer <apiKey>`. */
  apiKey?: string;
}

/** Error thrown when the API returns a non-2xx response. */
export class PharmacopeiaError extends Error {
  readonly code?: string;
  readonly status: number;
  readonly details?: unknown;

  constructor(
    message: string,
    init: { code?: string; status: number; details?: unknown },
  ) {
    super(message);
    this.name = "PharmacopeiaError";
    this.code = init.code;
    this.status = init.status;
    this.details = init.details;
  }
}

interface RequestOptions {
  query?: Record<string, string | number | boolean | undefined>;
  body?: unknown;
}

function toQueryString(
  query?: Record<string, string | number | boolean | undefined>,
): string {
  if (!query) return "";
  const parts: string[] = [];
  for (const [key, value] of Object.entries(query)) {
    if (value === undefined || value === null) continue;
    parts.push(`${encodeURIComponent(key)}=${encodeURIComponent(String(value))}`);
  }
  return parts.length ? `?${parts.join("&")}` : "";
}

/**
 * Thin, fully-typed client for the pharmacopeia API. Every method returns
 * the same shape the API serves; non-2xx responses throw
 * `PharmacopeiaError` carrying the API error `code` and `details`.
 */
export class PharmacopeiaClient {
  private readonly baseUrl: string;
  private readonly fetchImpl: typeof fetch;
  private readonly headers: Record<string, string>;

  constructor(options: PharmacopeiaClientOptions = {}) {
    this.baseUrl = (options.baseUrl ?? DEFAULT_BASE_URL).replace(/\/$/, "");
    this.fetchImpl = options.fetch ?? globalThis.fetch;
    if (!this.fetchImpl) {
      throw new Error(
        "No fetch implementation found. Pass `fetch` via options.",
      );
    }
    this.headers = {
      Accept: "application/json",
      ...(options.apiKey ? { Authorization: `Bearer ${options.apiKey}` } : {}),
      ...options.headers,
    };
  }

  private async request<T>(
    method: string,
    path: string,
    options: RequestOptions,
  ): Promise<T> {
    const url = `${this.baseUrl}${path}${toQueryString(options.query)}`;
    const headers: Record<string, string> = { ...this.headers };
    let body: string | undefined;
    if (options.body !== undefined) {
      headers["Content-Type"] = "application/json";
      body = JSON.stringify(options.body);
    }

    const res = await this.fetchImpl(url, { method, headers, body });
    if (!res.ok) {
      let payload: unknown;
      try {
        payload = await res.json();
      } catch {
        payload = undefined;
      }
      const err = (payload as { error?: { code?: string; message?: string; details?: unknown } } | undefined)?.error;
      throw new PharmacopeiaError(err?.message ?? res.statusText, {
        code: err?.code,
        status: res.status,
        details: err?.details,
      });
    }
    return (await res.json()) as T;
  }

  /** List drugs (paginated), optionally filtered by class or ingredient. */
  listDrugs(query: { limit?: number; offset?: number; class?: string; ingredient?: string } = {}): Promise<DrugListResponse> {
    return this.request<DrugListResponse>("GET", `/drugs`, { query });
  }

  /** Fetch a single drug by slug. */
  getDrug(slug: string, query: { fields?: string } = {}): Promise<Drug> {
    return this.request<Drug>("GET", `/drug/${encodeURIComponent(slug)}`, { query });
  }

  /** Fetch up to 100 drug records in a single round-trip. Returns the full records found plus the slugs that did not resolve. */
  getDrugsBatch(body: DrugsBatchRequest): Promise<DrugsBatchResponse> {
    return this.request<DrugsBatchResponse>("POST", `/drugs/batch`, { body });
  }

  /** List known interactions for a drug. */
  getDrugInteractions(slug: string): Promise<DrugInteractionsResponse> {
    return this.request<DrugInteractionsResponse>("GET", `/drug/${encodeURIComponent(slug)}/interactions`, {});
  }

  /** Structurally similar drugs (Tanimoto over 2D fingerprints). */
  getSimilarDrugs(slug: string): Promise<SimilarDrugsResponse> {
    return this.request<SimilarDrugsResponse>("GET", `/drug/${encodeURIComponent(slug)}/similar`, {});
  }

  /** List drug classes (paginated). */
  listClasses(query: { limit?: number; offset?: number } = {}): Promise<ClassListResponse> {
    return this.request<ClassListResponse>("GET", `/classes`, { query });
  }

  /** Fetch a single drug class plus the drugs it contains. */
  getClass(slug: string): Promise<ClassDetailResponse> {
    return this.request<ClassDetailResponse>("GET", `/class/${encodeURIComponent(slug)}`, {});
  }

  /** List active ingredients (paginated). */
  listIngredients(query: { limit?: number; offset?: number } = {}): Promise<IngredientListResponse> {
    return this.request<IngredientListResponse>("GET", `/ingredients`, { query });
  }

  /** Fetch a single ingredient by slug. */
  getIngredient(slug: string): Promise<Ingredient> {
    return this.request<Ingredient>("GET", `/ingredient/${encodeURIComponent(slug)}`, {});
  }

  /** Brand → generic crosswalk for every brand in the dataset. */
  listBrands(): Promise<BrandsResponse> {
    return this.request<BrandsResponse>("GET", `/brands`, {});
  }

  /** Dataset counts and version metadata. */
  getStats(): Promise<Stats> {
    return this.request<Stats>("GET", `/stats`, {});
  }

  /** Liveness + dataset-version probe. Tiny payload for monitors and clients. */
  getHealth(): Promise<HealthResponse> {
    return this.request<HealthResponse>("GET", `/health`, {});
  }

  /** Full-text search across drugs, classes, and ingredients. */
  search(query: { q: string; limit?: number }): Promise<SearchResponse> {
    return this.request<SearchResponse>("GET", `/search`, { query });
  }

  /** Check a set of 2–20 drug slugs for pairwise interactions. */
  checkInteractions(body: InteractionCheckRequest): Promise<InteractionCheckResponse> {
    return this.request<InteractionCheckResponse>("POST", `/interactions/check`, { body });
  }

  /** Rank drugs in the dataset by 2D Tanimoto similarity to a caller-supplied SMILES. Structural proximity only. */
  structureSearch(body: StructureSearchRequest): Promise<StructureSearchResponse> {
    return this.request<StructureSearchResponse>("POST", `/structure-search`, { body });
  }

  /** FDA shortage entries (active, resolved, discontinuation) for a drug. Reference statistics only. */
  getDrugShortages(slug: string): Promise<DrugShortagesResponse> {
    return this.request<DrugShortagesResponse>("GET", `/drug/${encodeURIComponent(slug)}/shortages`, {});
  }

  /** Every shortage entry across the dataset, sorted by drug then presentation. */
  listShortages(): Promise<ShortagesResponse> {
    return this.request<ShortagesResponse>("GET", `/shortages`, {});
  }

  /** Aggregate FAERS report counts for a drug — top reactions by reporting volume. NOT incidence rates, signals, or causality. */
  getDrugAdverseEvents(slug: string): Promise<AdverseEventStatsResponse> {
    return this.request<AdverseEventStatsResponse>("GET", `/drug/${encodeURIComponent(slug)}/adverse-events`, {});
  }

  /** Curated PubMed references for a drug, pinned to MeSH major topic at ingest time. */
  getDrugLiterature(slug: string): Promise<DrugLiteratureResponse> {
    return this.request<DrugLiteratureResponse>("GET", `/drug/${encodeURIComponent(slug)}/literature`, {});
  }

  /** Browse MedDRA Preferred Terms reported to FAERS across the dataset, ordered by total reporting volume. Reference statistics only — NOT a symptom checker. */
  listReactions(query: { limit?: number; offset?: number } = {}): Promise<ReactionsListResponse> {
    return this.request<ReactionsListResponse>("GET", `/reactions`, { query });
  }

  /** Fetch one MedDRA Preferred Term with its per-drug breakdown (count + share of matched FAERS reports), related reactions ranked by Jaccard similarity over the drug-id sets, and optional reference metadata — NLM MeSH descriptor id, scope note, tree position, and recent PubMed papers on the term as a MeSH major topic. Alias slugs 301-redirect to canonical. */
  getReaction(slug: string): Promise<ReactionResponse> {
    return this.request<ReactionResponse>("GET", `/reaction/${encodeURIComponent(slug)}`, {});
  }

  /** Meaning-based retrieval over drug-record passages. Embedding-backed when available; lexical fallback otherwise — `method` in the response reports which. */
  semanticSearch(query: { q: string; limit?: number; sections?: string }): Promise<SemanticSearchResponse> {
    return this.request<SemanticSearchResponse>("GET", `/semantic-search`, { query });
  }

  /** Key-gated retrieval tier for LLM consumers: same passages as /semantic-search plus per-span citations carrying full provenance (source URL, content hash, extraction timestamp, confidence). */
  groundedRetrieval(body: GroundedRequest): Promise<GroundedResponse> {
    return this.request<GroundedResponse>("POST", `/grounded`, { body });
  }

  /** List the webhook endpoints registered by the calling API key. */
  listWebhooks(): Promise<WebhooksListResponse> {
    return this.request<WebhooksListResponse>("GET", `/webhooks`, {});
  }

  /** Register a webhook endpoint. The response includes the HMAC signing secret exactly once — store it. */
  createWebhook(body: WebhookCreateRequest): Promise<WebhookEndpointCreated> {
    return this.request<WebhookEndpointCreated>("POST", `/webhooks`, { body });
  }

  /** Delete a webhook endpoint owned by the calling API key. */
  deleteWebhook(id: string): Promise<WebhookDeleteResponse> {
    return this.request<WebhookDeleteResponse>("DELETE", `/webhooks/${encodeURIComponent(id)}`, {});
  }

  /** Recent record-level changes (typed mirror of /feed.xml and /feed.json). */
  listChangelog(query: { limit?: number; since?: string } = {}): Promise<ChangelogResponse> {
    return this.request<ChangelogResponse>("GET", `/changelog`, { query });
  }
}
