// AUTO-GENERATED by `npm run codegen`. Do not edit by hand.
// Source of truth: lib/schemas/*.ts + lib/sdk/manifest.ts

export type Jurisdiction = "US-FDA" | "EU-EMA" | "UK-MHRA" | "CA-HC";

export type Severity = "contraindicated" | "major" | "moderate" | "minor" | "unknown";

export type DrugClassKind = "atc" | "moa" | "epc" | "pe" | "pharm" | "mesh";

export interface Provenance {
  sourceUrl: string;
  sourceHash: string;
  extractedAt: string;
  extractor: string;
  confidence: number;
}

export interface Pagination {
  total: number;
  limit: number;
  offset: number;
}

export interface ApiError {
  error: { code: "not_found" | "invalid_request" | "rate_limited" | "internal_error"; message: string; details?: unknown };
}

export interface DrugRef {
  slug: string;
  name: string;
}

export interface Indication {
  text: string;
  icd10: string[];
}

export interface Contraindication {
  text: string;
  severity: Severity;
}

export interface Dosing {
  route: "oral" | "iv" | "im" | "subcutaneous" | "topical" | "inhaled" | "intranasal" | "rectal" | "ophthalmic" | "otic" | "transdermal" | "other";
  population: "adult" | "pediatric" | "geriatric" | "renal-impairment" | "hepatic-impairment" | "pregnancy";
  condition?: string;
  dose: string;
  frequency?: string;
  maxDose?: string;
  notes?: string;
}

export interface Pharmacokinetics {
  halfLife?: string;
  tMax?: string;
  bioavailability?: string;
  proteinBinding?: string;
  metabolism?: string;
  excretion?: string;
}

export interface Mechanism {
  summary: string;
  targets: string[];
}

export interface Approval {
  date: string;
  applicationNumber: string;
  type: "NDA" | "ANDA" | "BLA" | "OTC";
  sponsor?: string;
}

export interface LabelSections {
  boxedWarning?: string;
  dosageAndAdministration?: string;
  warningsAndPrecautions?: string;
  adverseReactions?: string;
  useInSpecificPopulations?: string;
  overdosage?: string;
}

export interface Identifier {
  rxcui?: string;
  ndc: string[];
  atc: string[];
  drugbank?: string;
  chembl?: string;
  pubchem?: string;
  unii?: string;
}

export interface ChemicalStructure {
  smiles: string;
  inchiKey?: string;
  iupacName?: string;
  pubchemCid?: number;
  structureSvgPath: string;
  provenance: Provenance;
}

export interface DrugClassRef {
  slug: string;
  name: string;
  kind: DrugClassKind;
  code?: string;
}

export interface DrugClassParent {
  slug: string;
  name: string;
}

export interface DrugClass {
  slug: string;
  name: string;
  kind: DrugClassKind;
  code?: string;
  description?: string;
  parent?: DrugClassParent | null;
  drugCount: number;
  provenance: Provenance;
}

export interface IngredientRef {
  slug: string;
  name: string;
  strength?: string;
}

export interface Ingredient {
  slug: string;
  name: string;
  synonyms: string[];
  rxcui?: string;
  unii?: string;
  smiles?: string;
  inchikey?: string;
  molecularFormula?: string;
  molecularWeight?: number;
  drugCount: number;
  provenance: Provenance;
}

export interface DrugSummary {
  slug: string;
  name: string;
  synonyms: string[];
  jurisdiction: Jurisdiction;
  ingredients: IngredientRef[];
  brands: string[];
  classes: DrugClassRef[];
  shortDescription?: string;
}

export interface Drug {
  slug: string;
  name: string;
  synonyms: string[];
  jurisdiction: Jurisdiction;
  ingredients: IngredientRef[];
  brands: string[];
  classes: DrugClassRef[];
  shortDescription?: string;
  mechanism?: Mechanism;
  indications: Indication[];
  contraindications: Contraindication[];
  dosing: Dosing[];
  pharmacokinetics?: Pharmacokinetics;
  approvalHistory: Approval[];
  patientSummary?: string;
  interactionsNarrative?: string;
  labelSections?: LabelSections;
  identifiers: Identifier;
  chemical?: ChemicalStructure;
  provenance: Provenance;
}

export interface DrugsBatchRequest {
  slugs: string[];
}

export interface DrugsBatchResponse {
  found: Drug[];
  missing: string[];
  total: number;
}

export interface Interaction {
  drugA: string;
  drugB: string;
  severity: Severity;
  mechanism?: string;
  description: string;
  recommendation?: string;
  evidenceSpan?: string;
  provenance: Provenance;
}

export interface InteractionSummary {
  contraindicated: number;
  major: number;
  moderate: number;
  minor: number;
  unknown: number;
}

export interface InteractionCheckRequest {
  drugs: string[];
}

export interface InteractionCheckResponse {
  input: string[];
  pairs: Interaction[];
  summary: InteractionSummary;
}

export interface Stats {
  drugs: number;
  classes: number;
  ingredients: number;
  interactions: number;
  indications: number;
  version: string;
  updatedAt: string;
}

export interface HealthResponse {
  status: "ok";
  version: string;
  updatedAt: string;
  time: string;
  uptime?: number;
  repository: "static" | "supabase";
  commit?: string;
  region?: string;
}

export interface SimilarDrugResult {
  slug: string;
  name: string;
  score: number;
  className?: string;
}

export interface BrandEntry {
  brand: string;
  drugs: DrugRef[];
}

export interface SearchResult {
  slug: string;
  name: string;
  kind: "drug" | "ingredient" | "class";
  description?: string;
}

export interface DrugListResponse {
  items: DrugSummary[];
  pagination: Pagination;
}

export interface ClassListResponse {
  items: DrugClass[];
  pagination: Pagination;
}

export interface IngredientListResponse {
  items: Ingredient[];
  pagination: Pagination;
}

export interface DrugInteractionsResponse {
  drug: DrugRef;
  interactions: Interaction[];
  total: number;
}

export interface SimilarDrugsResponse {
  drug: DrugRef;
  method: "tanimoto-2d-fingerprint";
  similar: SimilarDrugResult[];
  total: number;
}

export interface ClassDetailResponse {
  slug: string;
  name: string;
  kind: DrugClassKind;
  code?: string;
  description?: string;
  parent?: DrugClassParent | null;
  drugCount: number;
  provenance: Provenance;
  drugs: DrugSummary[];
}

export interface BrandsResponse {
  brands: BrandEntry[];
  total: number;
}

export interface SearchResponse {
  query: string;
  results: SearchResult[];
  total: number;
}

export interface StructureMatch {
  slug: string;
  name: string;
  score: number;
  className?: string;
  smiles: string;
}

export interface StructureSearchRequest {
  smiles: string;
  limit: number;
  threshold: number;
}

export interface StructureSearchResponse {
  query: { smiles: string; limit: number; threshold: number };
  method: "tanimoto-2d-fingerprint";
  total: number;
  results: StructureMatch[];
}

export type ChangelogKind = "drug" | "class" | "ingredient" | "interaction" | "structure" | "dataset" | "endpoint";

export type ChangelogAction = "added" | "updated" | "removed" | "released";

export interface ChangelogEntry {
  id: string;
  kind: ChangelogKind;
  action: ChangelogAction;
  entitySlug?: string;
  title: string;
  summary: string;
  timestamp: string;
  url: string;
  sources: string[];
  tags: string[];
}

export interface ChangelogResponse {
  entries: ChangelogEntry[];
  total: number;
}

export type ShortageStatus = "active" | "resolved" | "discontinuation" | "to-be-discontinued";

export interface ShortageEntry {
  drug: string;
  status: ShortageStatus;
  presentation: string;
  sponsor?: string;
  reason?: string;
  therapeuticCategory?: string;
  fdaUpdatedAt: string;
  provenance: Provenance;
}

export interface DrugShortagesResponse {
  drug: { slug: string; name: string };
  entries: ShortageEntry[];
  anyActive: boolean;
  total: number;
}

export interface ShortagesResponse {
  entries: ShortageEntry[];
  total: number;
}

export interface AdverseEventReport {
  reaction: string;
  count: number;
}

export interface AdverseEventStats {
  drug: string;
  totalReports: number;
  topReactions: AdverseEventReport[];
  windowStart?: string;
  windowEnd?: string;
  disclaimer: string;
  provenance: Provenance;
}

export interface AdverseEventStatsResponse {
  drug: { slug: string; name: string };
  stats: AdverseEventStats | null;
}

export interface LiteratureReference {
  pmid: string;
  title: string;
  journal: string;
  year: number;
  authors: string[];
  doi?: string;
  pubmedUrl: string;
}

export interface DrugLiteratureResponse {
  drug: { slug: string; name: string };
  references: LiteratureReference[];
  total: number;
}

export interface ReactionSummary {
  slug: string;
  name: string;
  aliases: string[];
  drugCount: number;
  totalReports: number;
}

export interface ReactionDrugRow {
  drug: string;
  name: string;
  count: number;
  share: number | null;
  drugTotalReports: number;
}

export interface RelatedReaction {
  slug: string;
  name: string;
  sharedDrugs: number;
  similarity: number;
}

export interface MeshTreeNode {
  uid: string;
  descriptorId: string;
  name: string;
}

export interface ReactionMeta {
  meshDescriptorId: string;
  meshUid: string;
  meshDescriptorName: string;
  meshEntryTerms: string[];
  scopeNote: string;
  treeNumbers: string[];
  parents: MeshTreeNode[];
  meshBrowserUrl: string;
  references: LiteratureReference[];
  provenance: Provenance;
}

export interface Reaction {
  slug: string;
  name: string;
  aliases: string[];
  drugCount: number;
  totalReports: number;
  drugs: ReactionDrugRow[];
  relatedReactions: RelatedReaction[];
  meta: ReactionMeta | null;
  disclaimer: string;
}

export interface ReactionsListResponse {
  items: ReactionSummary[];
  pagination: Pagination;
}

export interface ReactionResponse {
  slug: string;
  name: string;
  aliases: string[];
  drugCount: number;
  totalReports: number;
  drugs: ReactionDrugRow[];
  relatedReactions: RelatedReaction[];
  meta: ReactionMeta | null;
  disclaimer: string;
}
