import type { Interaction } from "@/lib/schemas";

/**
 * Auto-generated by scripts/ingest/fetch-interactions.ts.
 *
 * Real drug-drug interactions are expensive to license (DrugBank,
 * Lexicomp, First Databank). The free public DDI source — RxNav's
 * /interaction API — was retired in 2024 when its Truven license
 * expired. The remaining free option is the per-drug narrative text
 * in the openFDA drug label "drug_interactions" section.
 *
 * That narrative is one-sided (it describes one drug's interaction
 * surface, not a `drugA × drugB` pair) and doesn't fit the pair-graph
 * `Interaction` schema. To preserve the v0 API contract we keep this
 * array empty and store the narrative on the Drug record itself
 * (`Drug.interactionsNarrative`) so the drug detail page can render
 * it.
 *
 * When a real pair-graph DDI source becomes available (DrugBank
 * partnership, ANSM file, etc.) this file gets rebuilt with real
 * `(drugA, drugB)` rows and `getDrugInteractions(slug)` starts
 * returning them.
 *
 * Edits to this file will be overwritten on the next
 * `npm run ingest:interactions`.
 */
export const SEED_INTERACTIONS: Interaction[] = [];
