// AUTO-GENERATED by scripts/ingest/fetch-similarity.ts
// Structural-similarity neighbours computed with OpenChemLib's 512-bit
// substructure index + Tanimoto coefficient over PubChem SMILES.
// Educational structural proximity only — NOT a claim of clinical or
// therapeutic equivalence. Re-run `npm run ingest:similarity` to refresh.

export interface SimilarDrug {
  slug: string;
  score: number;
}

export const SEED_SIMILARITY: Record<string, SimilarDrug[]> = {
  "alfuzosin": [{ slug: "terazosin", score: 0.798 }], // Alfuzosin
  "alprazolam": [{ slug: "diazepam", score: 0.831 }], // Alprazolam
  "amantadine": [{ slug: "memantine", score: 0.973 }], // Amantadine
  "amitriptyline": [{ slug: "nortriptyline", score: 0.879 }, { slug: "cyclobenzaprine", score: 0.844 }], // Amitriptyline
  "amlodipine": [{ slug: "felodipine", score: 0.927 }, { slug: "nifedipine", score: 0.835 }, { slug: "nicardipine", score: 0.783 }], // Amlodipine
  "amoxicillin": [{ slug: "ampicillin", score: 0.966 }, { slug: "cephalexin", score: 0.753 }], // Amoxicillin
  "ampicillin": [{ slug: "amoxicillin", score: 0.966 }, { slug: "cephalexin", score: 0.777 }], // Ampicillin
  "atenolol": [{ slug: "metoprolol", score: 0.903 }, { slug: "betaxolol", score: 0.829 }, { slug: "bisoprolol", score: 0.801 }, { slug: "propranolol", score: 0.772 }], // Atenolol
  "atomoxetine": [{ slug: "fluoxetine", score: 0.803 }], // Atomoxetine
  "azithromycin": [{ slug: "erythromycin", score: 0.932 }, { slug: "clarithromycin", score: 0.923 }, { slug: "clindamycin", score: 0.792 }, { slug: "tacrolimus", score: 0.787 }, { slug: "tiotropium", score: 0.784 }], // Azithromycin
  "beclomethasone": [{ slug: "mometasone", score: 0.995 }, { slug: "dexamethasone", score: 0.985 }, { slug: "triamcinolone", score: 0.976 }, { slug: "methylprednisolone", score: 0.947 }, { slug: "prednisolone", score: 0.946 }, { slug: "hydrocortisone", score: 0.909 }, { slug: "prednisone", score: 0.896 }, { slug: "fluticasone", score: 0.811 }], // Beclomethasone
  "benazepril": [{ slug: "enalapril", score: 0.766 }, { slug: "quinapril", score: 0.758 }], // Benazepril
  "betaxolol": [{ slug: "metoprolol", score: 0.911 }, { slug: "atenolol", score: 0.829 }, { slug: "bisoprolol", score: 0.797 }, { slug: "propranolol", score: 0.757 }], // Betaxolol
  "bisoprolol": [{ slug: "metoprolol", score: 0.856 }, { slug: "atenolol", score: 0.801 }, { slug: "propranolol", score: 0.799 }, { slug: "betaxolol", score: 0.797 }], // Bisoprolol
  "brimonidine": [{ slug: "clonidine", score: 0.91 }], // Brimonidine
  "budesonide": [{ slug: "triamcinolone", score: 0.777 }, { slug: "fluticasone", score: 0.774 }, { slug: "digoxin", score: 0.771 }, { slug: "dexamethasone", score: 0.769 }, { slug: "beclomethasone", score: 0.766 }, { slug: "mometasone", score: 0.762 }, { slug: "methylprednisolone", score: 0.759 }, { slug: "prednisolone", score: 0.758 }], // Budesonide
  "buprenorphine": [{ slug: "morphine", score: 0.922 }, { slug: "codeine", score: 0.917 }, { slug: "naltrexone", score: 0.847 }, { slug: "hydromorphone", score: 0.842 }, { slug: "naloxone", score: 0.837 }, { slug: "hydrocodone", score: 0.832 }, { slug: "oxymorphone", score: 0.831 }, { slug: "oxycodone", score: 0.826 }], // Buprenorphine
  "canagliflozin": [{ slug: "dapagliflozin", score: 0.808 }, { slug: "empagliflozin", score: 0.79 }], // Canagliflozin
  "cefdinir": [{ slug: "ceftriaxone", score: 0.989 }, { slug: "cefuroxime", score: 0.948 }, { slug: "cephalexin", score: 0.871 }], // Cefdinir
  "ceftriaxone": [{ slug: "cefdinir", score: 0.989 }, { slug: "cefuroxime", score: 0.958 }, { slug: "cephalexin", score: 0.869 }], // Ceftriaxone
  "cefuroxime": [{ slug: "ceftriaxone", score: 0.958 }, { slug: "cefdinir", score: 0.948 }, { slug: "cephalexin", score: 0.841 }], // Cefuroxime
  "cephalexin": [{ slug: "cefdinir", score: 0.871 }, { slug: "ceftriaxone", score: 0.869 }, { slug: "cefuroxime", score: 0.841 }, { slug: "ampicillin", score: 0.777 }, { slug: "amoxicillin", score: 0.753 }], // Cephalexin
  "cetirizine": [{ slug: "levocetirizine", score: 1 }, { slug: "hydroxyzine", score: 0.912 }], // Cetirizine
  "ciprofloxacin": [{ slug: "levofloxacin", score: 0.824 }], // Ciprofloxacin
  "citalopram": [{ slug: "escitalopram", score: 1 }], // Citalopram
  "clarithromycin": [{ slug: "erythromycin", score: 0.982 }, { slug: "azithromycin", score: 0.923 }, { slug: "tacrolimus", score: 0.766 }], // Clarithromycin
  "clindamycin": [{ slug: "ramipril", score: 0.801 }, { slug: "azithromycin", score: 0.792 }], // Clindamycin
  "clonazepam": [{ slug: "diazepam", score: 0.75 }], // Clonazepam
  "clonidine": [{ slug: "brimonidine", score: 0.91 }], // Clonidine
  "clozapine": [{ slug: "quetiapine", score: 0.766 }], // Clozapine
  "codeine": [{ slug: "morphine", score: 0.994 }, { slug: "buprenorphine", score: 0.917 }, { slug: "hydrocodone", score: 0.873 }, { slug: "hydromorphone", score: 0.873 }, { slug: "oxycodone", score: 0.841 }, { slug: "oxymorphone", score: 0.836 }, { slug: "naloxone", score: 0.822 }, { slug: "naltrexone", score: 0.822 }], // Codeine
  "cyclobenzaprine": [{ slug: "amitriptyline", score: 0.844 }], // Cyclobenzaprine
  "dapagliflozin": [{ slug: "empagliflozin", score: 0.966 }, { slug: "canagliflozin", score: 0.808 }], // Dapagliflozin
  "desvenlafaxine": [{ slug: "venlafaxine", score: 0.965 }], // Desvenlafaxine
  "dexamethasone": [{ slug: "triamcinolone", score: 0.99 }, { slug: "beclomethasone", score: 0.985 }, { slug: "mometasone", score: 0.981 }, { slug: "methylprednisolone", score: 0.951 }, { slug: "prednisolone", score: 0.951 }, { slug: "hydrocortisone", score: 0.913 }, { slug: "prednisone", score: 0.9 }, { slug: "fluticasone", score: 0.822 }], // Dexamethasone
  "diazepam": [{ slug: "alprazolam", score: 0.831 }, { slug: "temazepam", score: 0.815 }, { slug: "clonazepam", score: 0.75 }, { slug: "lorazepam", score: 0.75 }, { slug: "oxazepam", score: 0.75 }], // Diazepam
  "digoxin": [{ slug: "budesonide", score: 0.771 }], // Digoxin
  "diphenhydramine": [{ slug: "orphenadrine", score: 0.853 }], // Diphenhydramine
  "doxazosin": [{ slug: "terazosin", score: 0.768 }], // Doxazosin
  "doxycycline": [{ slug: "minocycline", score: 0.906 }], // Doxycycline
  "dutasteride": [{ slug: "finasteride", score: 0.773 }], // Dutasteride
  "empagliflozin": [{ slug: "dapagliflozin", score: 0.966 }, { slug: "canagliflozin", score: 0.79 }], // Empagliflozin
  "enalapril": [{ slug: "lisinopril", score: 0.927 }, { slug: "ramipril", score: 0.917 }, { slug: "quinapril", score: 0.874 }, { slug: "fosinopril", score: 0.801 }, { slug: "benazepril", score: 0.766 }], // Enalapril
  "erythromycin": [{ slug: "clarithromycin", score: 0.982 }, { slug: "azithromycin", score: 0.932 }, { slug: "tacrolimus", score: 0.752 }], // Erythromycin
  "escitalopram": [{ slug: "citalopram", score: 1 }], // Escitalopram
  "esomeprazole": [{ slug: "omeprazole", score: 1 }, { slug: "pantoprazole", score: 0.838 }], // Esomeprazole
  "felodipine": [{ slug: "amlodipine", score: 0.927 }, { slug: "nifedipine", score: 0.85 }, { slug: "nicardipine", score: 0.788 }], // Felodipine
  "finasteride": [{ slug: "dutasteride", score: 0.773 }], // Finasteride
  "fluoxetine": [{ slug: "atomoxetine", score: 0.803 }], // Fluoxetine
  "fluticasone": [{ slug: "triamcinolone", score: 0.823 }, { slug: "dexamethasone", score: 0.822 }, { slug: "mometasone", score: 0.815 }, { slug: "beclomethasone", score: 0.811 }, { slug: "methylprednisolone", score: 0.789 }, { slug: "prednisolone", score: 0.781 }, { slug: "budesonide", score: 0.774 }, { slug: "prednisone", score: 0.757 }], // Fluticasone
  "folic-acid": [{ slug: "methotrexate", score: 0.828 }], // Folic Acid
  "fosinopril": [{ slug: "ramipril", score: 0.866 }, { slug: "lisinopril", score: 0.804 }, { slug: "enalapril", score: 0.801 }, { slug: "tacrolimus", score: 0.783 }], // Fosinopril
  "galantamine": [{ slug: "codeine", score: 0.786 }, { slug: "morphine", score: 0.78 }, { slug: "buprenorphine", score: 0.75 }], // Galantamine
  "glipizide": [{ slug: "glyburide", score: 0.816 }], // Glipizide
  "glyburide": [{ slug: "glipizide", score: 0.816 }], // Glyburide
  "hydrocodone": [{ slug: "hydromorphone", score: 0.989 }, { slug: "oxycodone", score: 0.952 }, { slug: "oxymorphone", score: 0.946 }, { slug: "naloxone", score: 0.931 }, { slug: "naltrexone", score: 0.931 }, { slug: "codeine", score: 0.873 }, { slug: "morphine", score: 0.867 }, { slug: "buprenorphine", score: 0.832 }], // Hydrocodone
  "hydrocortisone": [{ slug: "prednisolone", score: 0.96 }, { slug: "methylprednisolone", score: 0.95 }, { slug: "dexamethasone", score: 0.913 }, { slug: "beclomethasone", score: 0.909 }, { slug: "triamcinolone", score: 0.905 }, { slug: "mometasone", score: 0.904 }, { slug: "prednisone", score: 0.898 }, { slug: "testosterone", score: 0.82 }], // Hydrocortisone
  "hydromorphone": [{ slug: "hydrocodone", score: 0.989 }, { slug: "oxymorphone", score: 0.957 }, { slug: "oxycodone", score: 0.952 }, { slug: "naloxone", score: 0.941 }, { slug: "naltrexone", score: 0.941 }, { slug: "morphine", score: 0.877 }, { slug: "codeine", score: 0.873 }, { slug: "buprenorphine", score: 0.842 }], // Hydromorphone
  "hydroxyzine": [{ slug: "cetirizine", score: 0.912 }, { slug: "levocetirizine", score: 0.912 }, { slug: "meclizine", score: 0.807 }], // Hydroxyzine
  "isosorbide-mononitrate": [{ slug: "topiramate", score: 0.827 }], // Isosorbide Mononitrate
  "isotretinoin": [{ slug: "tretinoin", score: 1 }], // Isotretinoin
  "itraconazole": [{ slug: "ketoconazole", score: 0.824 }], // Itraconazole
  "ketoconazole": [{ slug: "itraconazole", score: 0.824 }], // Ketoconazole
  "levocetirizine": [{ slug: "cetirizine", score: 1 }, { slug: "hydroxyzine", score: 0.912 }], // Levocetirizine
  "levodopa": [{ slug: "levothyroxine", score: 0.828 }, { slug: "liothyronine", score: 0.828 }], // Levodopa
  "levofloxacin": [{ slug: "ciprofloxacin", score: 0.824 }], // Levofloxacin
  "levothyroxine": [{ slug: "liothyronine", score: 1 }, { slug: "levodopa", score: 0.828 }], // Levothyroxine
  "linezolid": [{ slug: "rivaroxaban", score: 0.793 }], // Linezolid
  "liothyronine": [{ slug: "levothyroxine", score: 1 }, { slug: "levodopa", score: 0.828 }], // Liothyronine
  "lisinopril": [{ slug: "enalapril", score: 0.927 }, { slug: "ramipril", score: 0.889 }, { slug: "quinapril", score: 0.818 }, { slug: "fosinopril", score: 0.804 }], // Lisinopril
  "lorazepam": [{ slug: "oxazepam", score: 1 }, { slug: "temazepam", score: 0.89 }, { slug: "diazepam", score: 0.75 }], // Lorazepam
  "losartan": [{ slug: "olmesartan", score: 0.782 }], // Losartan
  "lovastatin": [{ slug: "simvastatin", score: 0.969 }, { slug: "pravastatin", score: 0.93 }, { slug: "spironolactone", score: 0.806 }], // Lovastatin
  "meclizine": [{ slug: "hydroxyzine", score: 0.807 }], // Meclizine
  "meloxicam": [{ slug: "piroxicam", score: 0.82 }], // Meloxicam
  "memantine": [{ slug: "amantadine", score: 0.973 }], // Memantine
  "methotrexate": [{ slug: "folic-acid", score: 0.828 }], // Methotrexate
  "methylprednisolone": [{ slug: "prednisolone", score: 0.99 }, { slug: "dexamethasone", score: 0.951 }, { slug: "hydrocortisone", score: 0.95 }, { slug: "beclomethasone", score: 0.947 }, { slug: "mometasone", score: 0.942 }, { slug: "triamcinolone", score: 0.942 }, { slug: "prednisone", score: 0.936 }, { slug: "fluticasone", score: 0.789 }], // Methylprednisolone
  "metoprolol": [{ slug: "betaxolol", score: 0.911 }, { slug: "atenolol", score: 0.903 }, { slug: "bisoprolol", score: 0.856 }, { slug: "propranolol", score: 0.827 }], // Metoprolol
  "minocycline": [{ slug: "doxycycline", score: 0.906 }], // Minocycline
  "mometasone": [{ slug: "beclomethasone", score: 0.995 }, { slug: "dexamethasone", score: 0.981 }, { slug: "triamcinolone", score: 0.971 }, { slug: "methylprednisolone", score: 0.942 }, { slug: "prednisolone", score: 0.941 }, { slug: "hydrocortisone", score: 0.904 }, { slug: "prednisone", score: 0.891 }, { slug: "fluticasone", score: 0.815 }], // Mometasone
  "morphine": [{ slug: "codeine", score: 0.994 }, { slug: "buprenorphine", score: 0.922 }, { slug: "hydromorphone", score: 0.877 }, { slug: "hydrocodone", score: 0.867 }, { slug: "oxymorphone", score: 0.84 }, { slug: "oxycodone", score: 0.836 }, { slug: "naloxone", score: 0.827 }, { slug: "naltrexone", score: 0.827 }], // Morphine
  "naloxone": [{ slug: "naltrexone", score: 0.989 }, { slug: "oxymorphone", score: 0.984 }, { slug: "oxycodone", score: 0.979 }, { slug: "hydromorphone", score: 0.941 }, { slug: "hydrocodone", score: 0.931 }, { slug: "buprenorphine", score: 0.837 }, { slug: "morphine", score: 0.827 }, { slug: "codeine", score: 0.822 }], // Naloxone
  "naltrexone": [{ slug: "naloxone", score: 0.989 }, { slug: "oxymorphone", score: 0.984 }, { slug: "oxycodone", score: 0.979 }, { slug: "hydromorphone", score: 0.941 }, { slug: "hydrocodone", score: 0.931 }, { slug: "buprenorphine", score: 0.847 }, { slug: "morphine", score: 0.827 }, { slug: "codeine", score: 0.822 }], // Naltrexone
  "nicardipine": [{ slug: "felodipine", score: 0.788 }, { slug: "amlodipine", score: 0.783 }, { slug: "nifedipine", score: 0.76 }], // Nicardipine
  "nifedipine": [{ slug: "felodipine", score: 0.85 }, { slug: "amlodipine", score: 0.835 }, { slug: "warfarin", score: 0.765 }, { slug: "nicardipine", score: 0.76 }], // Nifedipine
  "nortriptyline": [{ slug: "amitriptyline", score: 0.879 }], // Nortriptyline
  "olmesartan": [{ slug: "losartan", score: 0.782 }], // Olmesartan
  "omeprazole": [{ slug: "esomeprazole", score: 1 }, { slug: "pantoprazole", score: 0.838 }], // Omeprazole
  "orphenadrine": [{ slug: "diphenhydramine", score: 0.853 }], // Orphenadrine
  "oxazepam": [{ slug: "lorazepam", score: 1 }, { slug: "temazepam", score: 0.89 }, { slug: "diazepam", score: 0.75 }], // Oxazepam
  "oxycodone": [{ slug: "oxymorphone", score: 0.995 }, { slug: "naloxone", score: 0.979 }, { slug: "naltrexone", score: 0.979 }, { slug: "hydrocodone", score: 0.952 }, { slug: "hydromorphone", score: 0.952 }, { slug: "codeine", score: 0.841 }, { slug: "morphine", score: 0.836 }, { slug: "buprenorphine", score: 0.826 }], // Oxycodone
  "oxymorphone": [{ slug: "oxycodone", score: 0.995 }, { slug: "naloxone", score: 0.984 }, { slug: "naltrexone", score: 0.984 }, { slug: "hydromorphone", score: 0.957 }, { slug: "hydrocodone", score: 0.946 }, { slug: "morphine", score: 0.84 }, { slug: "codeine", score: 0.836 }, { slug: "buprenorphine", score: 0.831 }], // Oxymorphone
  "paliperidone": [{ slug: "risperidone", score: 0.855 }], // Paliperidone
  "pantoprazole": [{ slug: "esomeprazole", score: 0.838 }, { slug: "omeprazole", score: 0.838 }], // Pantoprazole
  "piroxicam": [{ slug: "meloxicam", score: 0.82 }], // Piroxicam
  "pravastatin": [{ slug: "lovastatin", score: 0.93 }, { slug: "simvastatin", score: 0.902 }, { slug: "spironolactone", score: 0.774 }], // Pravastatin
  "prednisolone": [{ slug: "methylprednisolone", score: 0.99 }, { slug: "hydrocortisone", score: 0.96 }, { slug: "dexamethasone", score: 0.951 }, { slug: "beclomethasone", score: 0.946 }, { slug: "triamcinolone", score: 0.942 }, { slug: "mometasone", score: 0.941 }, { slug: "prednisone", score: 0.926 }, { slug: "testosterone", score: 0.783 }], // Prednisolone
  "prednisone": [{ slug: "methylprednisolone", score: 0.936 }, { slug: "prednisolone", score: 0.926 }, { slug: "dexamethasone", score: 0.9 }, { slug: "hydrocortisone", score: 0.898 }, { slug: "beclomethasone", score: 0.896 }, { slug: "triamcinolone", score: 0.892 }, { slug: "mometasone", score: 0.891 }, { slug: "testosterone", score: 0.788 }], // Prednisone
  "propranolol": [{ slug: "metoprolol", score: 0.827 }, { slug: "bisoprolol", score: 0.799 }, { slug: "atenolol", score: 0.772 }, { slug: "betaxolol", score: 0.757 }], // Propranolol
  "propylthiouracil": [{ slug: "tizanidine", score: 0.778 }], // Propylthiouracil
  "quetiapine": [{ slug: "clozapine", score: 0.766 }], // Quetiapine
  "quinapril": [{ slug: "enalapril", score: 0.874 }, { slug: "lisinopril", score: 0.818 }, { slug: "ramipril", score: 0.814 }, { slug: "benazepril", score: 0.758 }], // Quinapril
  "ramipril": [{ slug: "enalapril", score: 0.917 }, { slug: "lisinopril", score: 0.889 }, { slug: "fosinopril", score: 0.866 }, { slug: "quinapril", score: 0.814 }, { slug: "clindamycin", score: 0.801 }, { slug: "tacrolimus", score: 0.751 }], // Ramipril
  "risperidone": [{ slug: "paliperidone", score: 0.855 }], // Risperidone
  "rivaroxaban": [{ slug: "linezolid", score: 0.793 }], // Rivaroxaban
  "rizatriptan": [{ slug: "sumatriptan", score: 0.787 }], // Rizatriptan
  "sildenafil": [{ slug: "vardenafil", score: 0.877 }], // Sildenafil
  "simvastatin": [{ slug: "lovastatin", score: 0.969 }, { slug: "pravastatin", score: 0.902 }, { slug: "spironolactone", score: 0.835 }], // Simvastatin
  "spironolactone": [{ slug: "simvastatin", score: 0.835 }, { slug: "lovastatin", score: 0.806 }, { slug: "pravastatin", score: 0.774 }], // Spironolactone
  "sumatriptan": [{ slug: "rizatriptan", score: 0.787 }], // Sumatriptan
  "tacrolimus": [{ slug: "azithromycin", score: 0.787 }, { slug: "fosinopril", score: 0.783 }, { slug: "tiotropium", score: 0.781 }, { slug: "clarithromycin", score: 0.766 }, { slug: "erythromycin", score: 0.752 }, { slug: "ramipril", score: 0.751 }], // Tacrolimus
  "temazepam": [{ slug: "lorazepam", score: 0.89 }, { slug: "oxazepam", score: 0.89 }, { slug: "diazepam", score: 0.815 }], // Temazepam
  "terazosin": [{ slug: "alfuzosin", score: 0.798 }, { slug: "doxazosin", score: 0.768 }], // Terazosin
  "testosterone": [{ slug: "hydrocortisone", score: 0.82 }, { slug: "prednisone", score: 0.788 }, { slug: "prednisolone", score: 0.783 }, { slug: "methylprednisolone", score: 0.775 }], // Testosterone
  "tiotropium": [{ slug: "azithromycin", score: 0.784 }, { slug: "tacrolimus", score: 0.781 }], // Tiotropium
  "tizanidine": [{ slug: "propylthiouracil", score: 0.778 }], // Tizanidine
  "topiramate": [{ slug: "isosorbide-mononitrate", score: 0.827 }], // Topiramate
  "tretinoin": [{ slug: "isotretinoin", score: 1 }], // Tretinoin
  "triamcinolone": [{ slug: "dexamethasone", score: 0.99 }, { slug: "beclomethasone", score: 0.976 }, { slug: "mometasone", score: 0.971 }, { slug: "methylprednisolone", score: 0.942 }, { slug: "prednisolone", score: 0.942 }, { slug: "hydrocortisone", score: 0.905 }, { slug: "prednisone", score: 0.892 }, { slug: "fluticasone", score: 0.823 }], // Triamcinolone
  "valacyclovir": [{ slug: "valganciclovir", score: 0.85 }], // Valacyclovir
  "valganciclovir": [{ slug: "valacyclovir", score: 0.85 }], // Valganciclovir
  "vardenafil": [{ slug: "sildenafil", score: 0.877 }], // Vardenafil
  "venlafaxine": [{ slug: "desvenlafaxine", score: 0.965 }], // Venlafaxine
  "warfarin": [{ slug: "nifedipine", score: 0.765 }], // Warfarin
};

export function getSeedSimilar(slug: string): SimilarDrug[] {
  return SEED_SIMILARITY[slug] ?? [];
}
