/**
 * scripts/ingest/fetch-drugs.ts
 *
 * Stage-0 ingest of the CURATED seed dataset (~300 widely-prescribed
 * drugs), emitted as TypeScript that is baked into the bundle and used
 * as the zero-config local fallback when DATABASE_URL is unset.
 *
 * The near-exhaustive 5,000+ drug dataset is produced by a separate
 * pipeline — `scripts/ingest/fetch-drugs-scale.ts` (`npm run ingest:scale`)
 * — which writes NDJSON artifacts loaded straight into Supabase. Both
 * pipelines share every fetcher and the record builder from
 * `scripts/ingest/shared.ts`, so a curated record and its scale-pipeline
 * counterpart are byte-identical.
 *
 * Sources: RxNav (NIH) + openFDA (label + drugsfda). Idempotent:
 * deterministic timestamps, sorted output, stable hashing. Re-running it
 * produces byte-identical files unless an upstream source changed.
 *
 * Run:   npm run ingest
 */

import "dotenv/config";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import type { Drug, DrugClass, Ingredient } from "../../lib/schemas";
import { CURATED_DRUG_NAMES } from "./curated-names";
import {
  COVERAGE_KEYS,
  type CoverageBits,
  finalizeDataset,
  ingestCandidate,
  sleep,
  slugify,
} from "./shared";

// ────────────────────────────────────────────────────────────────────────
// Paths and constants
// ────────────────────────────────────────────────────────────────────────

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, "../..");
const OUT_DIR = resolve(REPO_ROOT, "lib/data/seed");

// Curated names live in curated-names.ts so the scale universe can rank them first.
const DRUG_NAMES = CURATED_DRUG_NAMES;

// ────────────────────────────────────────────────────────────────────────
// Per-drug ingest (thin wrapper over the shared builder, with logging)
// ────────────────────────────────────────────────────────────────────────

interface IngestOk {
  ok: true;
  drug: Drug;
  ingredient: Ingredient;
  classes: DrugClass[];
  coverage: CoverageBits;
}
interface IngestFail {
  ok: false;
  reason: string;
}
type IngestResult = IngestOk | IngestFail;

async function ingestOne(name: string, idx: number, total: number): Promise<IngestResult> {
  const slug = slugify(name);
  const tag = `[${idx + 1}/${total}] ${slug}`;
  process.stderr.write(`${tag}: resolving RxCUI...\n`);

  let built;
  try {
    built = await ingestCandidate(name);
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    process.stderr.write(`${tag}: ✗ ${msg}\n`);
    return { ok: false, reason: `error: ${msg}` };
  }
  if (!built) {
    process.stderr.write(`${tag}: ✗ no RxNav result, skipping\n`);
    return { ok: false, reason: "no-rxcui" };
  }

  const { drug, ingredient, classes, coverage } = built;
  const badges = [
    `rxcui=${drug.identifiers.rxcui}`,
    `brands=${drug.brands.length}`,
    `classes=${drug.classes.length}`,
    coverage.label ? "label=yes" : "label=no",
    coverage.mechanism ? "mech=yes" : "mech=no",
    `approvals=${drug.approvalHistory.length}`,
    coverage.boxedWarning ? "bw=yes" : "bw=no",
  ].join(" ");
  process.stderr.write(`${tag}: ✓ ${badges}\n`);

  return { ok: true, drug, ingredient, classes, coverage };
}

// ────────────────────────────────────────────────────────────────────────
// Emit pretty TypeScript files
// ────────────────────────────────────────────────────────────────────────

const SAFE_KEY = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/;

function emitTs(value: unknown, indent = 0): string {
  const pad = "  ".repeat(indent);
  const pad1 = "  ".repeat(indent + 1);
  if (value === null) return "null";
  if (value === undefined) return "undefined";
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    const items = value.map((v) => pad1 + emitTs(v, indent + 1));
    return "[\n" + items.join(",\n") + ",\n" + pad + "]";
  }
  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>).filter(
      ([, v]) => v !== undefined,
    );
    if (entries.length === 0) return "{}";
    const lines = entries.map(([k, v]) => {
      const key = SAFE_KEY.test(k) ? k : JSON.stringify(k);
      return pad1 + key + ": " + emitTs(v, indent + 1);
    });
    return "{\n" + lines.join(",\n") + ",\n" + pad + "}";
  }
  throw new Error(`emitTs: unsupported value ${typeof value}`);
}

const HEADER_DRUGS = `import type { Drug } from "@/lib/schemas";

/**
 * Auto-generated by scripts/ingest/fetch-drugs.ts.
 *
 * Stage-0 drug records ingested from RxNav (RxCUI / brands / classes /
 * ATC codes / derived MOA targets), the openFDA drug label API
 * (mechanism, indications, contraindications, pharmacokinetics, plus
 * verbatim boxed-warning / dosage / adverse-reaction / warnings /
 * special-population / overdosage sections, NDC + UNII), and the
 * openFDA drugsfda API (approval history).
 *
 * Edits to this file will be overwritten on the next \`npm run ingest\`.
 * To curate a record by hand, drop it from the ingest list and move it
 * to a separate manually-edited seed file.
 *
 * Provenance:
 *   - openfda  : drug-level narrative fields (confidence 0.85)
 *   - rxnorm   : ingredients (confidence 0.95)
 *   - rxclass  : class memberships (confidence 0.95)
 *
 * IMPORTANT: This data is for development and illustrative use only.
 * It is not a clinical reference and must not be used to make medication
 * decisions.
 */
`;

const HEADER_CLASSES = `import type { DrugClass } from "@/lib/schemas";

/**
 * Auto-generated by scripts/ingest/fetch-drugs.ts. Derived from the
 * class memberships of every ingested drug (ATC, EPC, MOA, PE) via
 * RxNav RxClass.
 */
`;

const HEADER_INGREDIENTS = `import type { Ingredient } from "@/lib/schemas";

/**
 * Auto-generated by scripts/ingest/fetch-drugs.ts. One ingredient per
 * ingested drug (mono-substance v0). RxCUIs and canonical names come
 * from RxNav properties.
 */
`;

function writeFile(filename: string, body: string): void {
  mkdirSync(OUT_DIR, { recursive: true });
  const path = resolve(OUT_DIR, filename);
  writeFileSync(path, body, "utf8");
  process.stderr.write(`wrote ${path}\n`);
}

// ────────────────────────────────────────────────────────────────────────
// Main
// ────────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  // PHARM_LIMIT lets dev runs target a small subset for fast iteration.
  const limit = Number.parseInt(process.env.PHARM_LIMIT ?? "", 10);
  const names = Number.isFinite(limit) && limit > 0
    ? DRUG_NAMES.slice(0, limit)
    : DRUG_NAMES;
  process.stderr.write(
    `Ingesting ${names.length} drugs from RxNav + openFDA...\n\n`,
  );

  const results: IngestOk[] = [];
  const coverage: Record<keyof CoverageBits, number> = {
    mechanism: 0,
    targets: 0,
    indications: 0,
    contraindications: 0,
    pharmacokinetics: 0,
    boxedWarning: 0,
    dosageNarrative: 0,
    adverseReactions: 0,
    approvalHistory: 0,
    atc: 0,
    brands: 0,
    label: 0,
  };
  const skipped: { name: string; reason: string }[] = [];

  for (let i = 0; i < names.length; i++) {
    const name = names[i];
    try {
      const res = await ingestOne(name, i, names.length);
      if (!res.ok) {
        skipped.push({ name, reason: res.reason });
      } else {
        results.push(res);
        for (const k of COVERAGE_KEYS) {
          if (res.coverage[k]) coverage[k] += 1;
        }
      }
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      process.stderr.write(`[${i + 1}/${names.length}] ${name}: ✗ error: ${msg}\n`);
      skipped.push({ name, reason: `error: ${msg}` });
    }
    // Be polite to upstream APIs (shared.ts also throttles per host).
    await sleep(150);
  }

  // Class aggregation, collision-safe slugs, deterministic order, and
  // re-validation all live in the shared finaliser so the curated and
  // scale pipelines can never drift.
  const { drugs, ingredients, classes } = finalizeDataset(results);

  // Emit files
  const drugsBody = `${HEADER_DRUGS}
export const SEED_DRUGS: Drug[] = ${emitTs(drugs)};

export const SEED_DRUGS_BY_SLUG: Record<string, Drug> = Object.fromEntries(
  SEED_DRUGS.map((d) => [d.slug, d]),
);
`;

  const classesBody = `${HEADER_CLASSES}
export const SEED_CLASSES: DrugClass[] = ${emitTs(classes)};

export const SEED_CLASSES_BY_SLUG: Record<string, DrugClass> = Object.fromEntries(
  SEED_CLASSES.map((c) => [c.slug, c]),
);
`;

  const ingredientsBody = `${HEADER_INGREDIENTS}
export const SEED_INGREDIENTS: Ingredient[] = ${emitTs(ingredients)};

export const SEED_INGREDIENTS_BY_SLUG: Record<string, Ingredient> =
  Object.fromEntries(SEED_INGREDIENTS.map((i) => [i.slug, i]));
`;

  if (process.env.PHARM_DRY_RUN === "1") {
    process.stderr.write(
      `DRY_RUN: validated ${drugs.length} drugs / ${ingredients.length} ingredients / ${classes.length} classes; not writing files.\n`,
    );
  } else {
    writeFile("drugs.ts", drugsBody);
    writeFile("classes.ts", classesBody);
    writeFile("ingredients.ts", ingredientsBody);
  }

  // Final summary
  const total = names.length;
  process.stderr.write(`\n──────── ingest summary ────────\n`);
  process.stderr.write(`drugs:        ${drugs.length}/${total}\n`);
  process.stderr.write(`ingredients:  ${ingredients.length}\n`);
  process.stderr.write(`classes:      ${classes.length}\n`);
  process.stderr.write(`\ncoverage (out of ${drugs.length} successful drugs):\n`);
  process.stderr.write(`  mechanism:          ${coverage.mechanism}/${drugs.length}\n`);
  process.stderr.write(`  mechanism targets:  ${coverage.targets}/${drugs.length}\n`);
  process.stderr.write(`  indications:        ${coverage.indications}/${drugs.length}\n`);
  process.stderr.write(`  contraindications:  ${coverage.contraindications}/${drugs.length}\n`);
  process.stderr.write(`  pharmacokinetics:   ${coverage.pharmacokinetics}/${drugs.length}\n`);
  process.stderr.write(`  boxed warning:      ${coverage.boxedWarning}/${drugs.length}\n`);
  process.stderr.write(`  dosage narrative:   ${coverage.dosageNarrative}/${drugs.length}\n`);
  process.stderr.write(`  adverse reactions:  ${coverage.adverseReactions}/${drugs.length}\n`);
  process.stderr.write(`  approval history:   ${coverage.approvalHistory}/${drugs.length}\n`);
  process.stderr.write(`  ATC code:           ${coverage.atc}/${drugs.length}\n`);
  process.stderr.write(`  brand names:        ${coverage.brands}/${drugs.length}\n`);
  process.stderr.write(`  openFDA label:      ${coverage.label}/${drugs.length}\n`);
  if (skipped.length) {
    process.stderr.write(`\nskipped (${skipped.length}):\n`);
    for (const s of skipped) {
      process.stderr.write(`  - ${s.name}: ${s.reason}\n`);
    }
  }
  process.stderr.write(`\nDone.\n`);
}

main().catch((e) => {
  process.stderr.write(`\nFATAL: ${e instanceof Error ? e.stack : String(e)}\n`);
  process.exit(1);
});
