/**
 * scripts/ingest/fetch-shortages.ts
 *
 * Pulls FDA drug-shortage records from openFDA and joins them onto the
 * existing drug records by openFDA substance / generic name, writing
 * the result to `lib/data/seed/shortages.ts`.
 *
 * All per-record logic (paging, status mapping, join keys, entry
 * building) lives in `lib/ingest/shortages.ts`, shared with the
 * scheduled cron route that refreshes Postgres. This script only owns
 * the TS-seed-file serialisation.
 *
 * Idempotent: deterministic timestamps, sorted output, stable hashing.
 * Re-running produces byte-identical files unless openFDA changed.
 *
 * Run:   npm run ingest:shortages
 */

import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import type { ShortageEntry } from "../../lib/schemas";
import {
  buildShortageCrosswalk,
  buildShortageEntries,
  fetchAllShortageRecords,
} from "../../lib/ingest/shortages";
import {
  enrichScaleMode,
  loadEnrichmentDrugs,
  writeEnrichmentNdjson,
} from "./enrich-shared";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, "../..");
const OUT_FILE = resolve(REPO_ROOT, "lib/data/seed/shortages.ts");

// Deterministic fixed timestamp so re-runs do not diff just because of
// clock. Refreshing per-record provenance.extractedAt would otherwise
// guarantee a noisy diff every single run.
const EXTRACTED_AT = "2026-05-28T00:00:00.000Z";

function emitSeed(entries: Map<string, ShortageEntry[]>): string {
  const slugs = [...entries.keys()].sort();
  const blocks = slugs.map((slug) => {
    const lines = entries.get(slug)!.map((e) => {
      const fields = [
        `      drug: ${JSON.stringify(e.drug)},`,
        `      status: ${JSON.stringify(e.status)},`,
        `      presentation: ${JSON.stringify(e.presentation)},`,
      ];
      if (e.sponsor) fields.push(`      sponsor: ${JSON.stringify(e.sponsor)},`);
      if (e.reason) fields.push(`      reason: ${JSON.stringify(e.reason)},`);
      if (e.therapeuticCategory) {
        fields.push(
          `      therapeuticCategory: ${JSON.stringify(e.therapeuticCategory)},`,
        );
      }
      fields.push(`      fdaUpdatedAt: ${JSON.stringify(e.fdaUpdatedAt)},`);
      fields.push(`      provenance: {`);
      fields.push(`        sourceUrl: ${JSON.stringify(e.provenance.sourceUrl)},`);
      fields.push(`        sourceHash: ${JSON.stringify(e.provenance.sourceHash)},`);
      fields.push(`        extractedAt: ${JSON.stringify(e.provenance.extractedAt)},`);
      fields.push(`        extractor: ${JSON.stringify(e.provenance.extractor)},`);
      fields.push(`        confidence: ${e.provenance.confidence},`);
      fields.push(`      },`);
      return `    {\n${fields.join("\n")}\n    },`;
    });
    return `  ${JSON.stringify(slug)}: [\n${lines.join("\n")}\n  ],`;
  });

  return `// AUTO-GENERATED by scripts/ingest/fetch-shortages.ts
// Source: openFDA drug/shortages — see provenance.sourceUrl on each entry.
// Do not edit by hand; re-run \`npm run ingest:shortages\` to refresh.
//
// Reference statistics only — FDA shortage status changes frequently.
// For a live view, consult the FDA drug shortages database directly:
// https://www.accessdata.fda.gov/scripts/drugshortages/

import type { ShortageEntry } from "@/lib/schemas";

/**
 * Shortage entries keyed by drug slug. A drug may have multiple
 * entries (one per affected presentation).
 */
export const SEED_SHORTAGES: Record<string, ShortageEntry[]> = {
${blocks.join("\n")}
};

export function getSeedShortages(slug: string): ShortageEntry[] {
  return SEED_SHORTAGES[slug] ?? [];
}

export function listAllSeedShortages(): ShortageEntry[] {
  const all: ShortageEntry[] = [];
  for (const entries of Object.values(SEED_SHORTAGES)) {
    all.push(...entries);
  }
  return all.sort((a, b) => {
    if (a.drug !== b.drug) return a.drug.localeCompare(b.drug);
    return a.presentation.localeCompare(b.presentation);
  });
}
`;
}

async function main(): Promise<void> {
  const scale = enrichScaleMode();
  const drugs = loadEnrichmentDrugs();
  process.stderr.write(
    `[fetch-shortages] mode=${scale ? "scale" : "static"} drugs=${drugs.length}\n`,
  );

  const records = await fetchAllShortageRecords((line) =>
    process.stderr.write(`[fetch-shortages] ${line}\n`),
  );
  const crosswalk = buildShortageCrosswalk(
    drugs.map((drug) => ({
      slug: drug.slug,
      names: [drug.name, ...drug.ingredients.map((i) => i.name)],
    })),
  );
  const { bySlug, total, unmatched, unknownStatus } = buildShortageEntries(
    records,
    crosswalk,
    EXTRACTED_AT,
  );
  process.stderr.write(
    `[fetch-shortages] ${records.length} openFDA rows → ` +
      `${total} entries / ${bySlug.size} drugs ` +
      `(skipped: ${unmatched} unmatched, ${unknownStatus} unknown-status)\n`,
  );

  if (scale) {
    // db:seed flattens shortages into one ShortageEntry[] keyed by
    // entry.drug, so the NDJSON artifact is exactly that flat list.
    const flat = [...bySlug.keys()]
      .sort()
      .flatMap((slug) => bySlug.get(slug)!);
    const path = writeEnrichmentNdjson("shortages.ndjson", flat);
    process.stderr.write(`[fetch-shortages] wrote ${flat.length} entries → ${path}\n`);
    return;
  }

  const text = emitSeed(bySlug);
  writeFileSync(OUT_FILE, text, "utf8");
  process.stderr.write(`[fetch-shortages] wrote ${OUT_FILE}\n`);
}

main().catch((err) => {
  const msg = err instanceof Error ? err.stack ?? err.message : String(err);
  process.stderr.write(`[fetch-shortages] FAILED: ${msg}\n`);
  process.exit(1);
});
