/**
 * scripts/ingest/fetch-adverse-events.ts
 *
 * Pulls aggregate FAERS (FDA Adverse Event Reporting System) counts
 * from openFDA for every drug in the dataset and writes the result to
 * `lib/data/seed/adverse-events.ts`.
 *
 * For each drug we issue two openFDA queries:
 *
 *   /drug/event.json?search=patient.drug.openfda.generic_name:"<name>"
 *     ?count=patient.reaction.reactionmeddrapt.exact&limit=25
 *
 *   /drug/event.json?search=patient.drug.openfda.generic_name:"<name>"
 *     &limit=1   (to read `meta.results.total`)
 *
 * The result is rounded to the top-N reactions per drug, stamped with
 * provenance, and serialised to disk.
 *
 * **Framing matters here.** Every record carries an inline disclaimer
 * field that travels with the data so downstream consumers can never
 * accidentally interpret these counts as incidence rates or signals.
 *
 * Per-record logic (query building, escaping, shaping, hashing) lives
 * in `lib/ingest/adverse-events.ts`, shared with the rotating cron
 * refresher — never duplicated. This script only owns the TS-seed
 * serialisation and the full-dataset walk.
 *
 * Tunables (env):
 *   FAERS_TOP_N       max reactions stored per drug (default 25, max 100)
 *   FAERS_THROTTLE_MS delay between requests          (default 100)
 *   FAERS_MAX_DRUGS   debug cap on drug count         (default Infinity)
 *   OPENFDA_API_KEY   optional; lifts the 1,000 req/day unkeyed cap
 *
 * Run: npm run ingest:adverse-events
 */

import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import type { AdverseEventStats } from "../../lib/schemas";
import { fetchAdverseEventStats } from "../../lib/ingest/adverse-events";
import {
  enrichScaleMode,
  loadEnrichmentDrugs,
  openCheckpoint,
} from "./enrich-shared";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, "../..");
const OUT_FILE = resolve(REPO_ROOT, "lib/data/seed/adverse-events.ts");

const EXTRACTED_AT = "2026-05-28T00:00:00.000Z";

const TOP_N = clampInt(process.env.FAERS_TOP_N, 25, 1, 100);
const THROTTLE_MS = clampInt(process.env.FAERS_THROTTLE_MS, 100, 0, 5000);
const MAX_DRUGS = clampInt(process.env.FAERS_MAX_DRUGS, Number.MAX_SAFE_INTEGER, 1, Number.MAX_SAFE_INTEGER);

function clampInt(
  raw: string | undefined,
  fallback: number,
  lo: number,
  hi: number,
): number {
  const n = raw == null ? NaN : Number.parseInt(raw, 10);
  if (!Number.isFinite(n)) return fallback;
  return Math.min(Math.max(Math.trunc(n), lo), hi);
}

async function sleep(ms: number): Promise<void> {
  if (ms <= 0) return;
  await new Promise((r) => setTimeout(r, ms));
}

function emitSeed(map: Map<string, AdverseEventStats>): string {
  const slugs = [...map.keys()].sort();
  const blocks = slugs.map((slug) => {
    const s = map.get(slug)!;
    const reactions = s.topReactions
      .map(
        (r) =>
          `      { reaction: ${JSON.stringify(r.reaction)}, count: ${r.count} },`,
      )
      .join("\n");
    const lines = [
      `  ${JSON.stringify(slug)}: {`,
      `    drug: ${JSON.stringify(s.drug)},`,
      `    totalReports: ${s.totalReports},`,
      `    topReactions: [`,
      reactions,
      `    ],`,
    ];
    if (s.windowStart) lines.push(`    windowStart: ${JSON.stringify(s.windowStart)},`);
    if (s.windowEnd) lines.push(`    windowEnd: ${JSON.stringify(s.windowEnd)},`);
    lines.push(`    disclaimer: ${JSON.stringify(s.disclaimer)},`);
    lines.push(`    provenance: {`);
    lines.push(`      sourceUrl: ${JSON.stringify(s.provenance.sourceUrl)},`);
    lines.push(`      sourceHash: ${JSON.stringify(s.provenance.sourceHash)},`);
    lines.push(`      extractedAt: ${JSON.stringify(s.provenance.extractedAt)},`);
    lines.push(`      extractor: ${JSON.stringify(s.provenance.extractor)},`);
    lines.push(`      confidence: ${s.provenance.confidence},`);
    lines.push(`    },`);
    lines.push(`  },`);
    return lines.join("\n");
  });

  return `// AUTO-GENERATED by scripts/ingest/fetch-adverse-events.ts
// Source: openFDA drug/event (FAERS) — see provenance.sourceUrl on each entry.
// Do not edit by hand; re-run \`npm run ingest:adverse-events\` to refresh.
//
// FAERS reports are voluntarily submitted and are NOT incidence rates,
// signals, or causal evidence. Counts reflect reporting volume, not
// how often a reaction occurs. Reference statistics only.
//
// For decision-grade use, consult openFDA / the FAERS Public Dashboard
// directly: https://open.fda.gov/data/faers/

import type { AdverseEventStats } from "@/lib/schemas";

/**
 * Aggregate FAERS counts keyed by drug slug.
 */
export const SEED_ADVERSE_EVENTS: Record<string, AdverseEventStats> = {
${blocks.join("\n")}
};

export function getSeedAdverseEvents(slug: string): AdverseEventStats | null {
  return SEED_ADVERSE_EVENTS[slug] ?? null;
}
`;
}

async function main(): Promise<void> {
  const scale = enrichScaleMode();
  const drugs = loadEnrichmentDrugs().slice(0, MAX_DRUGS);
  process.stderr.write(
    `[fetch-adverse-events] mode=${scale ? "scale" : "static"} ` +
      `processing ${drugs.length} drugs (topN=${TOP_N}, throttle=${THROTTLE_MS}ms)\n`,
  );

  // Scale runs are long and resumable; the curated run stays in-memory.
  const checkpoint = scale
    ? openCheckpoint<AdverseEventStats>(
        "adverse-events.checkpoint.ndjson",
        "adverse-events.ndjson",
      )
    : null;
  const out = new Map<string, AdverseEventStats>();
  let withData = 0;
  let withoutData = 0;
  let processed = 0;

  for (const drug of drugs) {
    processed += 1;
    if (checkpoint?.done(drug.slug)) continue;

    const stats = await fetchAdverseEventStats(drug.slug, drug.name, {
      topN: TOP_N,
      extractedAt: EXTRACTED_AT,
      apiKey: process.env.OPENFDA_API_KEY,
      log: (line) => process.stderr.write(`  ! ${line}\n`),
    });
    if (stats) {
      out.set(drug.slug, stats);
      withData += 1;
    } else {
      withoutData += 1;
    }
    checkpoint?.record(drug.slug, stats ?? null);
    if (processed % 100 === 0 || !checkpoint) {
      process.stderr.write(
        `  [${processed}/${drugs.length}] ${drug.slug}: ${stats ? `${stats.totalReports} reports` : "no data"}\n`,
      );
    }
    await sleep(THROTTLE_MS);
  }

  if (checkpoint) {
    const path = checkpoint.flush();
    process.stderr.write(
      `[fetch-adverse-events] wrote ${checkpoint.size} drugs with data → ${path}\n`,
    );
    return;
  }

  const text = emitSeed(out);
  writeFileSync(OUT_FILE, text, "utf8");
  process.stderr.write(
    `[fetch-adverse-events] wrote ${OUT_FILE} ` +
      `(${withData} with data, ${withoutData} without)\n`,
  );
}

main().catch((err) => {
  const msg = err instanceof Error ? err.stack ?? err.message : String(err);
  process.stderr.write(`[fetch-adverse-events] FAILED: ${msg}\n`);
  process.exit(1);
});
