/**
 * scripts/ingest/fetch-pgx.ts
 *
 * Crosswalks every drug in the dataset to its CPIC-curated
 * pharmacogenomic drug–gene pairs via the public CPIC API
 * (api.cpicpgx.org, PostgREST). Results are written to
 * `lib/data/seed/pgx.ts`.
 *
 * Strategy:
 *  - One bulk fetch of the `pair_view` table (a few hundred rows),
 *    then a local join: primary key is the drug's RxCUI (CPIC drugid
 *    is `RxNorm:<rxcui>`), with a lowercased-name fallback for drugs
 *    whose seed RxCUI differs from CPIC's concept choice.
 *  - Pairs sort by gene symbol so output is stable.
 *
 * Idempotent: deterministic provenance.extractedAt, sorted output,
 * stable hashing. Re-runs against an unchanged CPIC release produce
 * byte-identical files.
 *
 * Run: npm run ingest:pgx
 */

import { writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  DrugPgxSchema,
  PgxPairSchema,
  type DrugPgx,
  type PgxPair,
  type Provenance,
} from "../../lib/schemas";
import {
  enrichScaleMode,
  loadEnrichmentDrugs,
  writeEnrichmentNdjson,
} from "./enrich-shared";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = resolve(__dirname, "../..");
const OUT_FILE = resolve(REPO_ROOT, "lib/data/seed/pgx.ts");

const EXTRACTED_AT = "2026-06-11T00:00:00.000Z";
const PAIR_VIEW_URL =
  "https://api.cpicpgx.org/v1/pair_view?order=pairid&limit=10000";

interface CpicPairRow {
  pairid?: number;
  drugid?: string;
  drugname?: string;
  genesymbol?: string;
  guidelinename?: string;
  guidelineurl?: string;
  cpiclevel?: string;
  clinpgxlevel?: string;
  pgxtesting?: string;
  pmids?: string[];
  provisional?: boolean;
}

function toPair(row: CpicPairRow): PgxPair | null {
  const gene = row.genesymbol?.trim();
  if (!gene) return null;
  const pair: PgxPair = {
    gene,
    ...(row.cpiclevel ? { cpicLevel: row.cpiclevel } : {}),
    ...(row.clinpgxlevel ? { clinpgxLevel: row.clinpgxlevel } : {}),
    ...(row.pgxtesting ? { fdaLabelTesting: row.pgxtesting } : {}),
    ...(row.guidelinename ? { guidelineName: row.guidelinename } : {}),
    ...(row.guidelineurl ? { guidelineUrl: row.guidelineurl } : {}),
    citations: row.pmids ?? [],
    provisional: row.provisional ?? false,
  };
  try {
    return PgxPairSchema.parse(pair);
  } catch {
    return null;
  }
}

function buildProvenance(drugName: string, genes: string[]): Provenance {
  const sourceHash = createHash("sha256")
    .update(JSON.stringify({ drug: drugName, genes }))
    .digest("hex");
  return {
    sourceUrl: PAIR_VIEW_URL,
    sourceHash,
    extractedAt: EXTRACTED_AT,
    extractor: "cpic-pair-view",
    confidence: 0.95,
  };
}

function emitSeed(map: Map<string, DrugPgx>): string {
  const slugs = [...map.keys()].sort();
  const body = slugs
    .map((slug) => {
      const entry = map.get(slug)!;
      return `  ${JSON.stringify(slug)}: ${JSON.stringify(entry, null, 2)
        .split("\n")
        .join("\n  ")},`;
    })
    .join("\n");

  return `// AUTO-GENERATED by scripts/ingest/fetch-pgx.ts
// Source: CPIC public API (api.cpicpgx.org pair_view) — see provenance.
// Do not edit by hand; re-run \`npm run ingest:pgx\` to refresh.
//
// Evidence metadata only. Levels describe curated evidence and
// guideline status, never testing or dosing guidance.

import type { DrugPgx } from "@/lib/schemas";

/**
 * CPIC drug–gene pair lists keyed by drug slug.
 */
export const SEED_PGX: Record<string, DrugPgx> = {
${body}
};

export function getSeedPgx(slug: string): DrugPgx | null {
  return SEED_PGX[slug] ?? null;
}
`;
}

async function main(): Promise<void> {
  process.stderr.write(`[fetch-pgx] fetching CPIC pair_view…\n`);
  const res = await fetch(PAIR_VIEW_URL, {
    headers: { Accept: "application/json" },
  });
  if (!res.ok) throw new Error(`CPIC pair_view HTTP ${res.status}`);
  const rows = (await res.json()) as CpicPairRow[];
  process.stderr.write(`[fetch-pgx] ${rows.length} pairs in registry\n`);

  const byRxcui = new Map<string, CpicPairRow[]>();
  const byName = new Map<string, CpicPairRow[]>();
  for (const row of rows) {
    const m = row.drugid?.match(/^RxNorm:(\d+)$/);
    if (m) {
      const list = byRxcui.get(m[1]) ?? [];
      list.push(row);
      byRxcui.set(m[1], list);
    }
    const name = row.drugname?.trim().toLowerCase();
    if (name) {
      const list = byName.get(name) ?? [];
      list.push(row);
      byName.set(name, list);
    }
  }

  const scale = enrichScaleMode();
  const drugs = loadEnrichmentDrugs();
  process.stderr.write(
    `[fetch-pgx] mode=${scale ? "scale" : "static"} joining ${drugs.length} drugs\n`,
  );

  const out = new Map<string, DrugPgx>();
  let withPairs = 0;

  for (const drug of drugs) {
    const rxcui = drug.identifiers.rxcui;
    const matched =
      (rxcui ? byRxcui.get(rxcui) : undefined) ??
      byName.get(drug.name.toLowerCase()) ??
      [];
    if (matched.length === 0) continue;

    const pairs = matched
      .map(toPair)
      .filter((p): p is PgxPair => p !== null)
      .sort((a, b) => a.gene.localeCompare(b.gene));
    if (pairs.length === 0) continue;

    const entry: DrugPgx = {
      drug: drug.slug,
      pairs,
      provenance: buildProvenance(
        drug.name,
        pairs.map((p) => p.gene),
      ),
    };
    DrugPgxSchema.parse(entry);
    out.set(drug.slug, entry);
    withPairs += 1;
    if (!scale) process.stderr.write(`  ${drug.slug}: ${pairs.length} gene pairs\n`);
  }

  if (scale) {
    const path = writeEnrichmentNdjson("pgx.ndjson", [...out.values()]);
    process.stderr.write(
      `[fetch-pgx] wrote ${withPairs} drugs with PGx pairs → ${path}\n`,
    );
    return;
  }

  const text = emitSeed(out);
  writeFileSync(OUT_FILE, text, "utf8");
  process.stderr.write(
    `[fetch-pgx] wrote ${OUT_FILE} (${withPairs} drugs with PGx pairs)\n`,
  );
}

main().catch((err) => {
  const msg = err instanceof Error ? err.stack ?? err.message : String(err);
  process.stderr.write(`[fetch-pgx] FAILED: ${msg}\n`);
  process.exit(1);
});
