import type { JsonSchemaObject, SchemaBundle } from "@/lib/sdk/registry";
import {
  API_BASE_PATH,
  DEFAULT_BASE_URL,
  OPERATIONS,
  type Operation,
  type QueryParam,
} from "@/lib/sdk/manifest";
import { isObjectNode, isOptional, refName } from "./util";

/**
 * Go SDK emitter. Turns the same Zod-derived schema bundle and route
 * manifest the TypeScript and Python clients are built from into a typed
 * Go client, so the Go SDK can never drift from the API contract either.
 */

const GEN_HEADER_GO =
  "// AUTO-GENERATED by `npm run codegen`. Do not edit by hand.\n" +
  "// Source of truth: lib/schemas/*.ts + lib/sdk/manifest.ts\n";

const GO_PACKAGE = "pharmacopeia";

/** PascalCase an arbitrary token for use as an exported Go identifier. */
function pascal(value: string): string {
  const parts = value.split(/[^a-zA-Z0-9]+/).filter(Boolean);
  const joined = parts
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("");
  return /^[0-9]/.test(joined) ? `_${joined}` : joined;
}

/** Exported Go field name from a JSON property key. */
function goFieldName(key: string): string {
  return pascal(key);
}

/** Map a JSON Schema node to a Go type expression. */
function goType(node: JsonSchemaObject, indent: string): string {
  if (node.$ref) return refName(node.$ref);
  if (node.const !== undefined) return "string";
  if (node.enum) return "string";

  if (node.anyOf) {
    const nonNull = node.anyOf.filter(
      (n) => !(n.type === "null" || (Array.isArray(n.type) && n.type.includes("null"))),
    );
    if (nonNull.length === 1) return goType(nonNull[0], indent);
    return "interface{}";
  }

  const type = node.type;
  if (Array.isArray(type)) {
    const nonNull = type.filter((t) => t !== "null");
    if (nonNull.length === 1) return goType({ ...node, type: nonNull[0] }, indent);
    return "interface{}";
  }

  switch (type) {
    case "array":
      return `[]${node.items ? goType(node.items, indent) : "interface{}"}`;
    case "object":
      if (node.properties) return goStruct(node, indent);
      return "map[string]interface{}";
    case "string":
      return "string";
    case "integer":
      return "int";
    case "number":
      return "float64";
    case "boolean":
      return "bool";
    case "null":
      return "interface{}";
    default:
      return "interface{}";
  }
}

/** Render an (anonymous or named-body) struct's field block. */
function goStruct(node: JsonSchemaObject, indent: string): string {
  const inner = indent + "\t";
  const lines = Object.entries(node.properties ?? {}).map(([key, child]) => {
    const optional = isOptional(node, key);
    const fieldType = goType(child, inner);
    // Optional scalars/structs become pointers so an absent value is
    // distinguishable from a zero value; slices, maps, and interfaces are
    // already nil-able, so they stay as-is.
    const isComposite =
      fieldType.startsWith("[]") ||
      fieldType.startsWith("map[") ||
      fieldType === "interface{}";
    const pointer = optional && !isComposite ? "*" : "";
    const tag = optional ? `${key},omitempty` : key;
    return `${inner}${goFieldName(key)} ${pointer}${fieldType} \`json:"${tag}"\``;
  });
  return `struct {\n${lines.join("\n")}\n${indent}}`;
}

function emitNamedType(name: string, node: JsonSchemaObject): string {
  if (isObjectNode(node)) {
    return `type ${name} ${goStruct(node, "")}`;
  }
  if (node.enum && Array.isArray(node.enum)) {
    const consts = node.enum
      .filter((v): v is string => typeof v === "string")
      .map((v) => `\t${name}${pascal(v)} ${name} = ${JSON.stringify(v)}`)
      .join("\n");
    return `type ${name} string\n\nconst (\n${consts}\n)`;
  }
  return `type ${name} ${goType(node, "")}`;
}

export function emitTypes(bundle: SchemaBundle): string {
  const blocks = bundle.order.map((name) =>
    emitNamedType(name, bundle.defs[name]),
  );
  return `${GEN_HEADER_GO}\npackage ${GO_PACKAGE}\n\n${blocks.join("\n\n")}\n`;
}

// ────────────────────────────────────────────────────────────────────────
// Client
// ────────────────────────────────────────────────────────────────────────

function goQueryArgType(q: QueryParam): string {
  return q.type === "number" ? "int" : "string";
}

/** Build the Go expression that assembles the request path. */
function goPathExpr(op: Operation): string {
  if (!op.pathParams || op.pathParams.length === 0) {
    return JSON.stringify(op.path);
  }
  // Split "/drug/{slug}/history" into string literals + escaped params.
  const parts: string[] = [];
  let buffer = "";
  const regex = /\{([^}]+)\}/g;
  let lastIndex = 0;
  let match: RegExpExecArray | null;
  while ((match = regex.exec(op.path)) !== null) {
    buffer += op.path.slice(lastIndex, match.index);
    parts.push(JSON.stringify(buffer));
    buffer = "";
    parts.push(`url.PathEscape(${match[1]})`);
    lastIndex = regex.lastIndex;
  }
  buffer += op.path.slice(lastIndex);
  if (buffer.length > 0) parts.push(JSON.stringify(buffer));
  return parts.join(" + ");
}

function emitMethod(op: Operation): string {
  const method = pascal(op.name);
  const args: string[] = [];
  for (const p of op.pathParams ?? []) args.push(`${p} string`);

  const requiredQuery = (op.queryParams ?? []).filter((q) => q.required);
  const optionalQuery = (op.queryParams ?? []).filter((q) => !q.required);
  for (const q of requiredQuery) {
    args.push(`${q.argName ?? q.name} ${goQueryArgType(q)}`);
  }
  if (op.requestSchema) args.push(`body ${op.requestSchema}`);
  if (optionalQuery.length > 0) args.push("opts url.Values");

  const bodyLines: string[] = [];
  const hasQuery = requiredQuery.length > 0 || optionalQuery.length > 0;
  if (hasQuery) {
    bodyLines.push(
      optionalQuery.length > 0
        ? "\tquery := cloneValues(opts)"
        : "\tquery := url.Values{}",
    );
    for (const q of requiredQuery) {
      const expr =
        q.type === "number"
          ? `strconv.Itoa(${q.argName ?? q.name})`
          : (q.argName ?? q.name);
      bodyLines.push(`\tquery.Set(${JSON.stringify(q.name)}, ${expr})`);
    }
  }

  const queryArg = hasQuery ? "query" : "nil";
  const bodyArg = op.requestSchema ? "body" : "nil";
  bodyLines.push(`\tvar out ${op.responseSchema}`);
  bodyLines.push(
    `\tif err := c.do(${JSON.stringify(op.method)}, ${goPathExpr(op)}, ${queryArg}, ${bodyArg}, &out); err != nil {`,
  );
  bodyLines.push("\t\treturn nil, err");
  bodyLines.push("\t}");
  bodyLines.push("\treturn &out, nil");

  const doc = `// ${method} ${op.summary}`;
  return `${doc}\nfunc (c *Client) ${method}(${args.join(", ")}) (*${op.responseSchema}, error) {\n${bodyLines.join("\n")}\n}`;
}

export function emitClient(): string {
  const methods = OPERATIONS.map(emitMethod).join("\n\n");
  // url is always used (PathEscape / Values); strconv only when a numeric
  // required query param exists.
  const needsStrconv = OPERATIONS.some((op) =>
    (op.queryParams ?? []).some((q) => q.required && q.type === "number"),
  );
  const imports = [
    '\t"bytes"',
    '\t"encoding/json"',
    '\t"fmt"',
    '\t"io"',
    '\t"net/http"',
    '\t"net/url"',
    '\t"strings"',
    ...(needsStrconv ? ['\t"strconv"'] : []),
  ].join("\n");

  return `${GEN_HEADER_GO}
package ${GO_PACKAGE}

import (
${imports}
)

// DefaultBaseURL is the public pharmacopeia API base (origin + ${API_BASE_PATH}).
const DefaultBaseURL = ${JSON.stringify(DEFAULT_BASE_URL)}

// Client is a thin, typed client for the pharmacopeia API. Every method
// returns the same shape the API serves; non-2xx responses return an
// *APIError carrying the API error code and details.
type Client struct {
	BaseURL    string
	HTTPClient *http.Client
	// APIKey, when set, is sent as "Authorization: Bearer <APIKey>".
	APIKey  string
	Headers map[string]string
}

// Option configures a Client.
type Option func(*Client)

// WithBaseURL overrides the API base URL.
func WithBaseURL(baseURL string) Option {
	return func(c *Client) { c.BaseURL = baseURL }
}

// WithAPIKey sets the bearer token used for key-gated endpoints.
func WithAPIKey(apiKey string) Option {
	return func(c *Client) { c.APIKey = apiKey }
}

// WithHTTPClient supplies a custom *http.Client.
func WithHTTPClient(hc *http.Client) Option {
	return func(c *Client) { c.HTTPClient = hc }
}

// NewClient builds a Client, applying any options over the defaults.
func NewClient(opts ...Option) *Client {
	c := &Client{BaseURL: DefaultBaseURL, HTTPClient: http.DefaultClient}
	for _, opt := range opts {
		opt(c)
	}
	if c.HTTPClient == nil {
		c.HTTPClient = http.DefaultClient
	}
	return c
}

// APIError is returned when the API responds with a non-2xx status.
type APIError struct {
	Status  int
	Code    string
	Message string
	Details interface{}
}

func (e *APIError) Error() string {
	if e.Code != "" {
		return fmt.Sprintf("pharmacopeia: %s (%s, status %d)", e.Message, e.Code, e.Status)
	}
	return fmt.Sprintf("pharmacopeia: %s (status %d)", e.Message, e.Status)
}

// cloneValues copies caller-supplied query values so required params can
// be layered on without mutating the caller's map.
func cloneValues(in url.Values) url.Values {
	out := url.Values{}
	for k, vs := range in {
		for _, v := range vs {
			out.Add(k, v)
		}
	}
	return out
}

func (c *Client) do(method, path string, query url.Values, body, out interface{}) error {
	endpoint := strings.TrimRight(c.BaseURL, "/") + path
	if len(query) > 0 {
		endpoint += "?" + query.Encode()
	}

	var reader io.Reader
	if body != nil {
		buf, err := json.Marshal(body)
		if err != nil {
			return err
		}
		reader = bytes.NewReader(buf)
	}

	req, err := http.NewRequest(method, endpoint, reader)
	if err != nil {
		return err
	}
	req.Header.Set("Accept", "application/json")
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	if c.APIKey != "" {
		req.Header.Set("Authorization", "Bearer "+c.APIKey)
	}
	for k, v := range c.Headers {
		req.Header.Set(k, v)
	}

	res, err := c.HTTPClient.Do(req)
	if err != nil {
		return err
	}
	defer res.Body.Close()

	data, err := io.ReadAll(res.Body)
	if err != nil {
		return err
	}

	if res.StatusCode < 200 || res.StatusCode >= 300 {
		apiErr := &APIError{Status: res.StatusCode, Message: res.Status}
		var envelope struct {
			Error struct {
				Code    string      \`json:"code"\`
				Message string      \`json:"message"\`
				Details interface{} \`json:"details"\`
			} \`json:"error"\`
		}
		if json.Unmarshal(data, &envelope) == nil && envelope.Error.Message != "" {
			apiErr.Code = envelope.Error.Code
			apiErr.Message = envelope.Error.Message
			apiErr.Details = envelope.Error.Details
		}
		return apiErr
	}

	if out != nil {
		if err := json.Unmarshal(data, out); err != nil {
			return err
		}
	}
	return nil
}

${methods}
`;
}
