import type { JsonSchemaObject } from "@/lib/sdk/registry";

export const GEN_HEADER_TS =
  "// AUTO-GENERATED by `npm run codegen`. Do not edit by hand.\n" +
  "// Source of truth: lib/schemas/*.ts + lib/sdk/manifest.ts\n";

export const GEN_HEADER_PY =
  "# AUTO-GENERATED by `npm run codegen`. Do not edit by hand.\n" +
  "# Source of truth: lib/schemas/*.ts + lib/sdk/manifest.ts\n";

/** Basename of a `#/$defs/<Name>` reference. */
export function refName(ref: string): string {
  const idx = ref.lastIndexOf("/");
  return idx === -1 ? ref : ref.slice(idx + 1);
}

/** camelCase / PascalCase -> snake_case. */
export function snakeCase(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1_$2")
    .toLowerCase();
}

/** A node is a structural object type we should emit as a model/interface. */
export function isObjectNode(node: JsonSchemaObject): boolean {
  return node.type === "object" && node.properties !== undefined;
}

export function isOptional(node: JsonSchemaObject, key: string): boolean {
  return !(node.required ?? []).includes(key);
}
